/*
 * File: app/store/StAddMyFlat.js
 * Date: Fri May 08 2015 19:53:52 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.store.StAddMyFlat', {
    extend: 'Ext.data.Store',
    alias: 'store.stAddMyFlat',

    requires: [
        'Ext.data.field.String'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'stAddMyFlat',
            autoLoad: true,
            data: [
                {
                    address: 'Добавить квартиру'
                }
            ],
            fields: [
                {
                    type: 'string',
                    name: 'address'
                }
            ]
        }, cfg)]);
    }
});