/*
 * File: app/view/FieldNach1.js
 * Date: Fri Mar 20 2015 09:30:40 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.view.FieldNach1', {
    extend: 'Ext.form.field.Number',
    alias: 'widget.fieldNach1',

    requires: [
        'yis.view.FieldNach1ViewModel',
        'yis.view.override.FieldNach1'
    ],

    viewModel: {
        type: 'fieldNach1'
    },
    width: 133,
    fieldLabel: 'label',
    labelWidth: 55,
    value: 0,
    fieldStyle: 'background-color:#F0F8FF;font-size:10pt;text-align:right;',
    hideTrigger: true,
    autoStripChars: true

});