/*
 * File: app/view/NFNach.js
 * Date: Wed Jan 13 2016 11:14:03 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.view.NFNach', {
    extend: 'Ext.form.field.Number',
    alias: 'widget.nFNach',

    requires: [
        'yis.view.NFNachViewModel',
        'yis.view.override.NFNach'
    ],

    viewModel: {
        type: 'nFNach'
    },
    width: 85,
    hideLabel: true,
    value: 0,
    fieldStyle: 'background-color:#F0F8FF;font-size:11pt;text-align:right;',
    hideTrigger: true,
    autoStripChars: true,
    decimalSeparator: '.'

});