/*
 * File: app/view/NFTarif1.js
 * Date: Wed Jan 13 2016 11:14:03 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.view.NFTarif1', {
    extend: 'Ext.form.field.Number',
    alias: 'widget.nFTarif1',

    requires: [
        'yis.view.NFTarif1ViewModel',
        'yis.view.override.NFTarif1'
    ],

    viewModel: {
        type: 'nFTarif1'
    },
    width: 70,
    fieldLabel: 'тариф',
    labelAlign: 'top',
    labelWidth: 50,
    value: 0,
    fieldStyle: 'background-color:#F0F8FF;font-size:10pt;text-align:right;',
    hideTrigger: true,
    decimalPrecision: 3,
    decimalSeparator: '.',
    step: 0.001

});