/*
 * File: app/model/MdAddress.js
 * Date: Fri Mar 20 2015 09:30:45 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.model.MdAddress', {
    extend: 'Ext.data.Model',
    alias: 'model.mdAddress',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            name: 'address_id'
        },
        {
            type: 'int',
            name: 'raion_id'
        },
        {
            type: 'int',
            name: 'house_id'
        },
        {
            type: 'string',
            name: 'address'
        },
        {
            type: 'string',
            name: 'appartment',
            sortType: 'asInt'
        },
        {
            type: 'string',
            name: 'app',
            sortType: 'asText'
        }
    ]
});