/*
 * File: app/model/MdLgotnik.js
 * Date: Fri Nov 27 2015 10:59:51 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.model.MdLgotnik', {
    extend: 'Ext.data.Model',
    alias: 'model.mdLgotnik',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'int',
            name: 'address_id'
        },
        {
            type: 'int',
            name: 'inn'
        },
        {
            type: 'int',
            name: 'kartochka'
        },
        {
            name: 'passport'
        },
        {
            type: 'string',
            name: 'fio'
        },
        {
            type: 'string',
            name: 'surname'
        },
        {
            type: 'string',
            name: 'firstname'
        },
        {
            type: 'string',
            name: 'lastname'
        },
        {
            type: 'string',
            name: 'surname_ua'
        },
        {
            type: 'string',
            name: 'firstname_ua'
        },
        {
            type: 'string',
            name: 'lastname_ua'
        },
        {
            type: 'string',
            name: 'document'
        },
        {
            type: 'string',
            name: 'lgota'
        },
        {
            type: 'int',
            name: 'category'
        },
        {
            type: 'int',
            name: 'people'
        },
        {
            name: 'percent'
        },
        {
            type: 'string',
            name: 'given'
        },
        {
            type: 'date',
            name: 'data'
        },
        {
            type: 'date',
            name: 'fdate'
        },
        {
            type: 'int',
            name: 'gr'
        },
        {
            type: 'string',
            name: 'vkl'
        },
        {
            type: 'int',
            name: 'raion'
        },
        {
            type: 'string',
            name: 'operator'
        },
        {
            type: 'date',
            name: 'date_in'
        },
        {
            type: 'date',
            name: 'start'
        },
        {
            type: 'date',
            name: 'finish'
        }
    ]
});