/*
 * File: app/model/MdOplata.js
 * Date: Thu Apr 19 2018 16:17:00 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.model.MdOplata', {
    extend: 'Ext.data.Model',
    alias: 'model.mdOPlata',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Number'
    ],

    fields: [
        {
            type: 'int',
            name: 'address_id'
        },
        {
            type: 'string',
            name: 'address'
        },
        {
            type: 'int',
            name: 'god'
        },
        {
            type: 'date',
            name: 'fdate'
        },
        {
            type: 'float',
            name: 'kvartplata'
        },
        {
            type: 'float',
            name: 'otoplenie'
        },
        {
            type: 'float',
            name: 'podogrev'
        },
        {
            type: 'float',
            name: 'voda'
        },
        {
            type: 'float',
            name: 'stoki'
        },
        {
            type: 'float',
            name: 'tbo'
        },
        {
            type: 'float',
            name: 'summa'
        },
        {
            type: 'string',
            name: 'prixod'
        },
        {
            type: 'string',
            name: 'kassa'
        },
        {
            type: 'string',
            name: 'nomer'
        },
        {
            type: 'string',
            name: 'operator'
        },
        {
            type: 'date',
            name: 'date_in'
        },
        {
            type: 'date',
            name: 'data'
        },
        {
            type: 'int',
            name: 'chek'
        },
        {
            type: 'int',
            name: 'rec_id'
        },
        {
            type: 'string',
            name: 'pr'
        },
        {
            type: 'int',
            name: 'payment_id'
        },
        {
            type: 'int',
            name: 'pay_id'
        },
        {
            type: 'string',
            name: 'status'
        },
        {
            type: 'int',
            name: 'commission'
        },
        {
            type: 'float',
            name: 'ptn'
        }
    ]
});