/*
 * File: app/model/MdWater.js
 * Date: Fri Mar 20 2015 09:30:45 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.model.MdWater', {
    extend: 'Ext.data.Model',
    alias: 'model.mdWater',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Number'
    ],

    fields: [
        {
            type: 'int',
            name: 'address_id'
        },
        {
            type: 'string',
            name: 'address'
        },
        {
            type: 'int',
            name: 'nomer'
        },
        {
            type: 'date',
            name: 'data'
        },
        {
            type: 'date',
            name: 'fdate'
        },
        {
            type: 'int',
            name: 'pred'
        },
        {
            type: 'int',
            name: 'tek'
        },
        {
            type: 'int',
            name: 'kub'
        },
        {
            type: 'float',
            name: 'tarif_xv'
        },
        {
            type: 'float',
            name: 'xvoda'
        },
        {
            type: 'float',
            name: 'tarif_gv'
        },
        {
            type: 'float',
            name: 'gvoda'
        },
        {
            type: 'float',
            name: 'tarif_st'
        },
        {
            type: 'float',
            name: 'stoki'
        },
        {
            type: 'int',
            name: 'xkub_lg'
        },
        {
            type: 'int',
            name: 'gkub_lg'
        },
        {
            type: 'float',
            name: 'lgota_xv'
        },
        {
            type: 'float',
            name: 'lgota_gv'
        },
        {
            type: 'float',
            name: 'lgota_st'
        },
        {
            type: 'string',
            name: 'operator'
        }
    ]
});