/*
 * File: app/view/user/TabReport.js
 * Date: Fri Mar 20 2015 09:30:40 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.view.user.TabReport', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabReport',

    requires: [
        'yis.view.user.TabReportViewModel',
        'Ext.panel.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'tabReport'
    },
    itemId: 'tabReport',
    layout: 'border',
    closable: true,
    collapseFirst: false,

    items: [
        {
            xtype: 'panel',
            flex: 1,
            region: 'center',
            minHeight: 100,
            scrollable: true,
            layout: 'fit',
            title: ''
        }
    ],
    dockedItems: [
        {
            xtype: 'toolbar',
            dock: 'top',
            minHeight: 40,
            resizable: true,
            items: [
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        var rep = Ext.REPORTCONTENT;
                        //console.log(rep);
                        var win = window.open('','printwin');
                        win.document.write(rep);
                        win.document.close();
                        if(Ext.isIE){

                            window.print();
                            // window.close();
                        } else {

                            win.print();
                            // win.close();
                        }

                    },
                    icon: 'resources/css/images/ico/print_printer.png',
                    scale: 'large',
                    text: 'Печать',
                    tooltip: 'Печать документа'
                }
            ]
        }
    ]

});