/*
 * File: app/view/user/WinAddMyFlat.js
 * Date: Thu Jul 30 2020 13:53:36 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.view.user.WinAddMyFlat', {
    extend: 'Ext.window.Window',
    alias: 'widget.winAddMyFlat',

    requires: [
        'yis.view.user.WinAddMyFlatViewModel',
        'yis.view.user.WinAddMyFlatViewController',
        'Ext.form.FieldSet',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Action',
        'Ext.grid.column.Number',
        'Ext.selection.RowModel'
    ],

    controller: 'winAddMyFlat',
    viewModel: {
        type: 'winAddMyFlat'
    },
    height: 637,
    hidden: false,
    id: 'winAddMyFlat',
    width: 501,
    layout: 'fit',
    bodyPadding: '5 5 5 5',
    title: 'Добавить мои квартиры ',
    modal: true,
    defaultListenerScope: true,

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: 'panel',
                        id: 'pnMyFlat',
                        itemId: 'pnMyFlat',
                        width: 500,
                        title: '',
                        layout: {
                            type: 'vbox',
                            align: 'stretch'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                height: 244,
                                layout: 'fit',
                                title: '',
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        height: 183,
                                        style: 'background-color: #DCDCDC;',
                                        width: 245,
                                        layout: 'absolute',
                                        title: 'выбор адреса',
                                        items: [
                                            {
                                                xtype: 'combobox',
                                                x: 5,
                                                y: 20,
                                                frame: true,
                                                id: 'cbViborRaion',
                                                width: 220,
                                                fieldLabel: 'район',
                                                hideEmptyLabel: false,
                                                labelPad: 3,
                                                labelWidth: 50,
                                                emptyText: 'Выбирите район',
                                                selectOnFocus: true,
                                                displayField: 'raion',
                                                queryMode: 'local',
                                                store: 'StRaion',
                                                valueField: 'raion_id',
                                                listeners: {
                                                    select: 'onCbViborRaionSelect'
                                                }
                                            },
                                            {
                                                xtype: 'combobox',
                                                x: 5,
                                                y: 80,
                                                frame: true,
                                                id: 'cbViborStreet',
                                                width: 220,
                                                fieldLabel: 'улица',
                                                hideEmptyLabel: false,
                                                labelPad: 3,
                                                labelWidth: 50,
                                                emptyText: 'Выбирите улицу',
                                                selectOnFocus: true,
                                                displayField: 'street',
                                                queryMode: 'local',
                                                store: 'StStreet',
                                                valueField: 'street_id',
                                                listeners: {
                                                    select: {
                                                        fn: 'onCbViborStreetSelect',
                                                        scope: 'controller'
                                                    }
                                                }
                                            },
                                            {
                                                xtype: 'combobox',
                                                x: 5,
                                                y: 140,
                                                frame: true,
                                                id: 'cbViborHouse',
                                                width: 220,
                                                fieldLabel: 'дом',
                                                hideEmptyLabel: false,
                                                labelPad: 3,
                                                labelWidth: 50,
                                                emptyText: 'Выбирите дом',
                                                selectOnFocus: true,
                                                displayField: 'house',
                                                queryMode: 'local',
                                                store: 'StHouses',
                                                valueField: 'house_id',
                                                listeners: {
                                                    select: {
                                                        fn: 'onCbViborHouseSelect',
                                                        scope: 'controller'
                                                    }
                                                }
                                            },
                                            {
                                                xtype: 'fieldset',
                                                x: 245,
                                                y: 5,
                                                height: 170,
                                                html: '<h5><p  style = "text-align: justify;">Чтобы добавить квартиру в список <i> мои квартиры </i>, Вам  нужно иметь <i>секретный код</i> . <br>Код можно получить в кассах приема коммунальных платежей при оплате.Код находится в левом верхнем углу распечатки об оплате.<p></h5>',
                                                style: 'background-color: #F1EEEE;',
                                                width: 200,
                                                title: ''
                                            },
                                            {
                                                xtype: 'button',
                                                handler: function(button, event) {
                                                    button.up('#winAddMyFlat').close();
                                                },
                                                x: 300,
                                                y: 180,
                                                height: 25,
                                                width: 100,
                                                icon: 'resources/css/images/ico/door_out.png',
                                                text: 'Выход'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                flex: 1,
                                height: 609,
                                width: 993,
                                layout: {
                                    type: 'hbox',
                                    align: 'stretch'
                                },
                                items: [
                                    {
                                        xtype: 'gridpanel',
                                        id: 'grAddress',
                                        scrollable: true,
                                        width: 250,
                                        title: 'Список квартир для добавления',
                                        enableColumnHide: false,
                                        enableColumnMove: false,
                                        enableColumnResize: false,
                                        sortableColumns: false,
                                        store: 'StAddress',
                                        columns: [
                                            {
                                                xtype: 'actioncolumn',
                                                draggable: false,
                                                width: 40,
                                                align: 'center',
                                                hideable: false,
                                                tooltip: 'добавить квартиру в список < Мои квартиры >',
                                                items: [
                                                    {
                                                        handler: function(view, rowIndex, colIndex, item, e) {
                                                            var stAddress = view.getStore().getAt(rowIndex);
                                                            var stUser = Ext.data.StoreManager.get("StUser");
                                                            var stlogin =stUser.getAt(0);

                                                            var stMyFlat = Ext.data.StoreManager.get("StMyFlat");
                                                            Ext.MessageBox.prompt(stAddress.get('address'),' Введите cекретный код квартиры:',
                                                            function(btn,text){
                                                                if (btn == 'ok') {
                                                                    QueryUserLogin.checkMyFlat(stAddress.data,stlogin.data,text,function(results){
                                                                        if (results.success){
                                                                            stMyFlat.load({
                                                                                params: {
                                                                                    user_id:stlogin.get('user_id')
                                                                                },
                                                                                scope:this
                                                                            });

                                                                        }else if (results.nokey){
                                                                            Ext.MessageBox.show({
                                                                                title: 'Моя квартира',
                                                                                msg: 'Секретный код неверный',
                                                                                buttons: Ext.MessageBox.OK,
                                                                                icon: Ext.MessageBox.ERROR
                                                                            });
                                                                        }else if (results.myflat){
                                                                            Ext.MessageBox.show({
                                                                                title: 'Моя квартира',
                                                                                msg: 'Квартира уже в списке',
                                                                                buttons: Ext.MessageBox.OK,
                                                                                icon: Ext.MessageBox.ERROR
                                                                            });
                                                                        }else if (results.noid){
                                                                            Ext.MessageBox.show({
                                                                                title: 'Моя квартира',
                                                                                msg: 'Ошибка при записи в базу данных',
                                                                                buttons: Ext.MessageBox.OK,
                                                                                icon: Ext.MessageBox.ERROR
                                                                            });
                                                                        }
                                                                    });
                                                                }
                                                            });
                                                        },
                                                        getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                                            metaData = 'x-grid-center-icon';
                                                            return metaData;
                                                        },
                                                        altText: 'добавить квартиру',
                                                        icon: 'resources/css/images/ico/add.png',
                                                        iconCls: 'icon-add',
                                                        tooltip: 'добавить квартиру в список < Мои квартиры >'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                hidden: true,
                                                dataIndex: 'address_id',
                                                text: 'Address_id'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                hidden: true,
                                                dataIndex: 'raion_id',
                                                text: 'Raion_id'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'address',
                                                text: 'Квартира',
                                                flex: 1
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                hidden: true,
                                                dataIndex: 'appartment',
                                                text: 'Appartment'
                                            }
                                        ],
                                        selModel: Ext.create('Ext.selection.RowModel', {
                                            selType: 'rowmodel'
                                        })
                                    },
                                    {
                                        xtype: 'gridpanel',
                                        height: 350,
                                        width: 220,
                                        title: 'Список мои квартиры',
                                        enableColumnHide: false,
                                        enableColumnMove: false,
                                        enableColumnResize: false,
                                        sortableColumns: false,
                                        store: 'StMyFlat',
                                        columns: [
                                            {
                                                xtype: 'actioncolumn',
                                                width: 40,
                                                align: 'center',
                                                tooltip: 'Удалить квартиру из списка',
                                                items: [
                                                    {
                                                        getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                                            metaData = 'x-grid-center-icon';
                                                            return metaData;
                                                        },
                                                        handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                                            var stMyFlat = view.getStore().getAt(rowIndex);
                                                            var stUser = Ext.data.StoreManager.get("StUser");
                                                            var stlogin =stUser.getAt(0);
                                                            var store = view.getStore();

                                                            Ext.MessageBox.confirm({
                                                                title: 'Удаление квартиры из списка < Мои квартиры >',
                                                                msg: 'Вы удаляете квартиру  '+ stMyFlat.get('address')+ '<br> Подтвердите или отмените свои действия.',
                                                                buttons: Ext.MessageBox.OKCANCEL,
                                                                icon: Ext.MessageBox.ERROR,
                                                                buttonText:{
                                                                    ok:'подтвеждаю',
                                                                    cancel:'отмена'
                                                                },
                                                                fn:function(btn,newValue){
                                                                    if(btn=='ok'){
                                                                        store.remove(record);
                                                                        store.sync({
                                                                            success: function(){
                                                                                Ext.MessageBox.show({title: 'Удаление записи',
                                                                                    msg:'Запись удалена',
                                                                                    buttons: Ext.MessageBox.OK,
                                                                                    icon: Ext.MessageBox.INFO
                                                                                });
                                                                            },
                                                                            failure: function(){
                                                                                Ext.MessageBox.show({title: 'Удаление записи',
                                                                                    msg:'Невозможно удалить',
                                                                                    buttons: Ext.MessageBox.OK,
                                                                                    icon: Ext.MessageBox.ERROR
                                                                                });

                                                                            },
                                                                            scope: this
                                                                        });
                                                                    }
                                                                }
                                                            });
                                                        },
                                                        icon: 'resources/css/images/ico/delete.png',
                                                        tooltip: 'Удалить квартиру из списка'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                hidden: true,
                                                dataIndex: 'address_id',
                                                text: 'Address_id'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                hidden: true,
                                                dataIndex: 'raion_id',
                                                text: 'Raion_id'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                hidden: true,
                                                dataIndex: 'house_id',
                                                text: 'House_id'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                dataIndex: 'address',
                                                text: 'квартира',
                                                flex: 1
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                hidden: true,
                                                dataIndex: 'appartment',
                                                text: 'Appartment'
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    onCbViborRaionSelect: function(combo, record, eOpts) {
        var StHouses = Ext.data.StoreManager.get("StHouses");
        var StStreet = Ext.data.StoreManager.get("StStreet");
        var StAddress = Ext.data.StoreManager.get("StAddress");

        var store =combo.getStore();

        var cbStreet = Ext.getCmp("cbViborStreet");
        var cbHouse = Ext.getCmp("cbViborHouse");

        var selected = record;
        if (selected && !store.getById(selected.get("raion_id"))) {
            StStreet.removeAll();
            StHouses.removeAll();
            StAddress.removeAll();
            cbStreet.clearValue();
            cbHouse.clearValue();


            StStreet.load({
                params: {
                    what:"StreetsFromRaion",
                    what_id: selected.get("raion_id")
                },
                scope: this
            });
            StHouses.load({
                params: {
                    what:"HousesFromRaion",
                    what_id: selected.get("raion_id")
                },
                scope: this
            });
        }

    }

});