/*
 * File: app/view/user/WinEmailConfirm.js
 * Date: Thu Jul 30 2020 13:53:36 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.view.user.WinEmailConfirm', {
    extend: 'Ext.window.Window',
    alias: 'widget.winEmailConfirm',

    requires: [
        'yis.view.user.WinEmailConfirmViewModel',
        'Ext.form.FieldSet',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'winEmailConfirm'
    },
    draggable: false,
    height: 405,
    id: 'winEmailConfirm',
    itemId: 'winEmailConfirm',
    width: 593,
    title: 'Почтовое уведомление',
    modal: true,
    plain: true,

    items: [
        {
            xtype: 'fieldset',
            height: 367,
            html: '<h4 class="email-confirm"><span>Продолжение регистрации</span><br><p style = "text-align: justify;">На Ваш электронный адрес выслано письмо с ссылкой для активации. Вам нужно в течение 3 дней перейти по ссылке для подтверждения регистрации. По истечению этого срока Ваша регистрационная запись будет удалена.<br>Спасибо за регистрацию !<brАдминистрация портала></p></h4>',
            padding: 30,
            style: 'background-color: #F1EEEE;',
            layout: 'absolute',
            title: '',
            items: [
                {
                    xtype: 'button',
                    x: 210,
                    y: 250,
                    cls: 'button',
                    id: 'btnConfirmEmailClose',
                    width: 145,
                    iconCls: 'icon-door-out ',
                    scale: 'medium',
                    text: 'Выход'
                }
            ]
        }
    ]

});