/*
 * File: app/view/flat/tabAppBti.js
 * Date: Fri Sep 18 2020 10:38:45 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.view.flat.tabAppBti', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabappbti',

    requires: [
        'yis.view.flat.tabAppBtiViewModel',
        'yis.view.flat.tabAppBtiViewController',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Number',
        'Ext.form.field.Checkbox',
        'Ext.form.field.TextArea',
        'Ext.form.field.Date',
        'Ext.form.field.Display',
        'Ext.form.field.Hidden'
    ],

    controller: 'tabappbti',
    viewModel: {
        type: 'tabappbti'
    },
    height: 805,
    id: 'tabAppBti',
    scrollable: true,
    width: 1096,
    title: 'БТІ',

    items: [
        {
            xtype: 'panel',
            scrollable: true,
            width: 1076,
            layout: 'anchor',
            title: '',
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'grLgotchikBti',
                    margin: '5 5 5 5',
                    scrollable: true,
                    collapseFirst: false,
                    collapsed: true,
                    collapsible: true,
                    title: 'Пільговики',
                    titleAlign: 'center',
                    titleCollapse: true,
                    emptyText: 'Льготников нет',
                    store: 'StLgotnik',
                    viewConfig: {
                        emptyText: 'Льготников нет'
                    },
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'lgotnik_id',
                            text: 'lgotnik_id',
                            format: '0'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'address_id',
                            text: 'Address_id'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return Ext.String.format('<div  <b>{0}</b>&nbsp;&nbsp;<span class="author">{1} </span><br><span class="author">{2}</span></div>',
                                value,
                                record.get('firstname') || "",
                                record.get('lastname') || "");
                            },
                            width: 251,
                            dataIndex: 'surname',
                            menuDisabled: true,
                            text: 'П.І.Б.'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return Ext.String.format('<div> <b>{0}</b><br><span class="author">{1} </span></div>',
                                value,
                                record.get('passport') || "");
                            },
                            width: 130,
                            dataIndex: 'inn',
                            menuDisabled: true,
                            text: 'інн / паспорт'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                metaData.style = 'white-space:pre-wrap;';
                                return value;

                            },
                            width: 264,
                            dataIndex: 'lgota',
                            menuDisabled: true,
                            text: 'Пільга'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'lgota_id',
                            text: 'Льгота_ид',
                            format: '0'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                var retValue = '';
                                if(value==="нет"){
                                    return Ext.String.format('<div ><span>вкл <img clas="icon" src="resources/css/images/ico/no.png"/></div>');

                                } else {
                                    return Ext.String.format('<div ><span>вкл <img clas="icon" src="resources/css/images/ico/yes.png"/></span></div>');
                                }
                            },
                            width: 71,
                            dataIndex: 'vkl',
                            menuDisabled: true,
                            text: 'вкл'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 62,
                            dataIndex: 'people',
                            menuDisabled: true,
                            text: 'чол',
                            format: '0'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 59,
                            dataIndex: 'percent',
                            menuDisabled: true,
                            text: '%',
                            format: '0'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 51,
                            dataIndex: 'gr',
                            menuDisabled: true,
                            text: 'Гр',
                            format: '0'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 51,
                            dataIndex: 'category',
                            menuDisabled: true,
                            text: 'Кат',
                            format: '0'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return Ext.String.format('<div > <span class="author">с {0}</span><br><span class="author">по {1}</span></div>',
                                Ext.Date.format(value, 'd-m-Y') ,
                                Ext.Date.format(record.get('finish'), 'd-m-Y') || "");
                            },
                            width: 97,
                            dataIndex: 'start',
                            menuDisabled: true,
                            text: 'Період'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    anchor: '100%',
                    id: 'grFamaly',
                    margin: '5 5 5 5',
                    scrollable: true,
                    width: 1052,
                    animCollapse: true,
                    collapsed: true,
                    collapsible: true,
                    iconAlign: 'right',
                    title: 'Склад квартиронаймачів',
                    titleAlign: 'center',
                    titleCollapse: true,
                    columnLines: true,
                    emptyText: 'записей нет',
                    store: 'StFamaly',
                    viewConfig: {
                        emptyText: ' Записей нет'
                    },
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'rec_id',
                            text: 'rec_id'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'address_id',
                            text: 'Address_id'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return Ext.String.format('<div  <b>{0}</b>&nbsp;&nbsp;<span class="author">{1} </span><br><span class="author">{2}</span></div>',
                                value,
                                record.get('firstname') || "",
                                record.get('lastname') || "");
                            },
                            width: 220,
                            dataIndex: 'surname',
                            menuDisabled: true,
                            text: 'Фамилия И. О.'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 157,
                            dataIndex: 'rodstvo',
                            menuDisabled: true,
                            text: 'родство'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 109,
                            dataIndex: 'inn',
                            menuDisabled: true,
                            text: 'инн'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            width: 100,
                            dataIndex: 'address',
                            menuDisabled: true,
                            text: 'адрес'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 101,
                            align: 'center',
                            dataIndex: 'born',
                            menuDisabled: true,
                            text: 'Дата рожд',
                            format: 'd-m-Y'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 103,
                            align: 'center',
                            dataIndex: 'datap',
                            menuDisabled: true,
                            text: 'Дата рег',
                            format: 'd-m-Y'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                return Ext.String.format('<div <b>{0} </b><br><span class="author">серия &nbsp; {1} номер &nbsp;&nbsp;&nbsp;</span><span class="author">{2}</span></div>',
                                value,
                                record.get('seria') || "",
                                record.get('nomer') || "");
                            },
                            width: 219,
                            dataIndex: 'document',
                            menuDisabled: true,
                            text: 'Документ'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                switch (value) {
                                    case "да":
                                    metaData='<span><img clas="icon" src="resources/css/images/ico/yes.png"/></span>';
                                    break;
                                    case "нет":
                                    metaData='<span><img clas="icon" src="resources/css/images/ico/no.png"/></span>';
                                    break;
                                }
                                return metaData;

                            },
                            width: 45,
                            align: 'center',
                            dataIndex: 'subsidia',
                            menuDisabled: true,
                            text: 'суб'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                switch (value) {
                                    case "да":
                                    metaData='<span><img clas="icon" src="resources/css/images/ico/yes.png"/></span>';
                                    break;
                                    case "нет":
                                    metaData='<span><img clas="icon" src="resources/css/images/ico/no.png"/></span>';
                                    break;
                                }
                                return metaData;

                            },
                            width: 45,
                            align: 'center',
                            dataIndex: 'vkl',
                            menuDisabled: true,
                            text: 'вкл'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                switch (value) {
                                    case 1:
                                    metaData='<span><img clas="icon" src="resources/css/images/ico/yes.png"/></span>';
                                    break;
                                    case 0:
                                    metaData='<span><img clas="icon" src="resources/css/images/ico/no.png"/></span>';
                                    break;
                                }
                                return metaData;

                            },
                            width: 40,
                            align: 'center',
                            dataIndex: 'absent',
                            menuDisabled: true,
                            text: 'отс'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    height: 647,
                    id: 'fmAppartment',
                    scrollable: true,
                    style: 'background-color: #e0e0e0;',
                    layout: 'fit',
                    title: '',
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 600,
                            margin: '5 5 5 5',
                            scrollable: true,
                            style: 'background-color: #DCDCDC;',
                            width: 1054,
                            layout: 'absolute',
                            title: 'Загальна інформація',
                            items: [
                                {
                                    xtype: 'fieldset',
                                    x: 5,
                                    y: 85,
                                    height: 175,
                                    style: 'background-color: #F1EEEE;',
                                    width: 455,
                                    layout: 'absolute',
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            x: 0,
                                            y: 10,
                                            width: 90,
                                            fieldLabel: 'Код',
                                            labelPad: 15,
                                            labelSeparator: ' ',
                                            labelWidth: 20,
                                            name: 'address_id',
                                            readOnly: true,
                                            editable: false,
                                            hideTrigger: true,
                                            allowDecimals: false,
                                            decimalPrecision: 0
                                        },
                                        {
                                            xtype: 'numberfield',
                                            x: 240,
                                            y: 135,
                                            height: 25,
                                            width: 190,
                                            fieldLabel: 'таємний код',
                                            labelSeparator: ' ',
                                            labelWidth: 80,
                                            name: 'kod',
                                            readOnly: true,
                                            editable: false,
                                            hideTrigger: true,
                                            maxLength: 15,
                                            allowDecimals: false,
                                            decimalPrecision: 0
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 0,
                                            y: 40,
                                            width: 430,
                                            fieldLabel: 'Гл. наймач',
                                            labelSeparator: ' ',
                                            labelWidth: 80,
                                            name: 'nanim'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 0,
                                            y: 70,
                                            width: 430,
                                            fieldLabel: 'Власник',
                                            labelSeparator: ' ',
                                            labelWidth: 80,
                                            name: 'owner'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 0,
                                            y: 100,
                                            width: 430,
                                            fieldLabel: 'Телефон',
                                            labelSeparator: ' ',
                                            labelWidth: 65,
                                            name: 'phone'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 0,
                                            y: 135,
                                            width: 235,
                                            fieldLabel: 'Email',
                                            labelSeparator: ' ',
                                            labelWidth: 40,
                                            name: 'email',
                                            emptyText: 'user@example.com',
                                            vtype: 'email'
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 100,
                                            y: 10,
                                            width: 330,
                                            fieldLabel: 'Адреса',
                                            labelSeparator: ' ',
                                            labelWidth: 50,
                                            name: 'address',
                                            editable: false
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    x: 465,
                                    y: 85,
                                    height: 215,
                                    style: 'background-color: #F1EEEE;',
                                    width: 510,
                                    layout: 'absolute',
                                    title: 'дані БТІ',
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            x: 0,
                                            y: 0,
                                            fieldLabel: 'Приват',
                                            labelWidth: 50,
                                            name: 'privat',
                                            boxLabel: 'Ні',
                                            inputValue: 'да',
                                            uncheckedValue: 'нет',
                                            listeners: {
                                                change: 'onCheckboxfieldChange'
                                            }
                                        },
                                        {
                                            xtype: 'textareafield',
                                            x: 110,
                                            y: 0,
                                            width: 375,
                                            fieldLabel: 'Ордер',
                                            labelAlign: 'top',
                                            labelSeparator: ' ',
                                            labelWidth: 120,
                                            name: 'order',
                                            grow: true
                                        },
                                        {
                                            xtype: 'datefield',
                                            x: 0,
                                            y: 25,
                                            width: 100,
                                            fieldLabel: 'Дата ордера',
                                            labelAlign: 'top',
                                            name: 'data_ordera',
                                            format: 'd-m-Y',
                                            submitFormat: 'Y-m-d'
                                        },
                                        {
                                            xtype: 'fieldset',
                                            x: 0,
                                            y: 90,
                                            height: 95,
                                            style: 'background-color: #DCDCDC;',
                                            width: 485,
                                            layout: 'absolute',
                                            title: 'Склад (людина)',
                                            items: [
                                                {
                                                    xtype: 'numberfield',
                                                    x: 5,
                                                    y: 5,
                                                    width: 135,
                                                    fieldLabel: 'Прописано',
                                                    labelSeparator: ' ',
                                                    labelWidth: 70,
                                                    name: 'tenant',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    allowDecimals: false,
                                                    decimalPrecision: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    x: 290,
                                                    y: 5,
                                                    width: 135,
                                                    fieldLabel: 'Відсутні',
                                                    labelSeparator: ' ',
                                                    labelWidth: 70,
                                                    name: 'absent',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    allowDecimals: false,
                                                    decimalPrecision: 0,
                                                    minValue: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    x: 155,
                                                    y: 5,
                                                    width: 120,
                                                    fieldLabel: 'Піднаймач',
                                                    labelSeparator: ' ',
                                                    labelWidth: 70,
                                                    name: 'podnan',
                                                    editable: false,
                                                    hideTrigger: true,
                                                    allowDecimals: false,
                                                    decimalPrecision: 0,
                                                    minValue: 0
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    x: 515,
                                                    y: 315,
                                                    fieldLabel: 'Льготник',
                                                    labelSeparator: ' ',
                                                    labelWidth: 70,
                                                    name: 'lgotchik',
                                                    allowDecimals: false,
                                                    decimalPrecision: 0,
                                                    minValue: 0
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    x: 5,
                                                    y: 35,
                                                    fieldLabel: 'Субсидія',
                                                    labelAlign: 'right',
                                                    labelWidth: 70,
                                                    name: 'subsidia',
                                                    boxLabel: 'Ні',
                                                    inputValue: 'да',
                                                    uncheckedValue: 'нет',
                                                    listeners: {
                                                        change: 'onCheckboxfieldChange'
                                                    }
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    renderer: function(value, displayField) {
                                                        var form = displayField.findParentByType('form');
                                                        var lg = form.getForm().findField('lgotchik').getValue();
                                                        //console.log(lg);
                                                        var retValue = '';
                                                        if(lg===0){
                                                            retValue ='<span><img class="icon" src="resources/css/images/ico/no.png"/></span>';
                                                        } else {
                                                            retValue ='<span><img class="icon" src="resources/css/images/ico/yes.png"/></span>';
                                                        }
                                                        return retValue;
                                                    },
                                                    x: 135,
                                                    y: 35,
                                                    width: 100,
                                                    fieldLabel: 'Пільга',
                                                    labelSeparator: ' ',
                                                    labelWidth: 70,
                                                    name: 'lgota'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldset',
                                    x: 5,
                                    y: 270,
                                    height: 125,
                                    style: 'background-color: #F1EEEE;',
                                    width: 455,
                                    layout: 'absolute',
                                    title: 'Паспортні дані',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            x: 0,
                                            y: 0,
                                            cls: 'bti',
                                            width: 140,
                                            fieldLabel: 'Серія №',
                                            labelSeparator: ' ',
                                            labelWidth: 60,
                                            name: 'passport'
                                        },
                                        {
                                            xtype: 'datefield',
                                            x: 145,
                                            y: 0,
                                            width: 150,
                                            fieldLabel: 'Дата',
                                            labelSeparator: ' ',
                                            labelWidth: 35,
                                            name: 'viddata',
                                            format: 'd-m-Y',
                                            submitFormat: 'Ymd'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            x: 10,
                                            y: 35,
                                            cls: 'bti',
                                            width: 420,
                                            fieldLabel: 'Видано',
                                            labelSeparator: ' ',
                                            labelWidth: 50,
                                            name: 'vidan',
                                            grow: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            x: 300,
                                            y: 0,
                                            width: 130,
                                            fieldLabel: 'Інн',
                                            labelSeparator: ' ',
                                            labelWidth: 30,
                                            name: 'inn'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    x: 465,
                                    y: 315,
                                    height: 265,
                                    id: 'grAppHistory',
                                    scrollable: true,
                                    width: 510,
                                    title: 'історія змін по квартирі',
                                    emptyText: 'Нет данных для просмотра',
                                    store: 'StHAppartment',
                                    viewConfig: {
                                        height: 138,
                                        id: 'grAppHistoryView'
                                    },
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'address_id',
                                            text: 'Address_id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'address',
                                            text: 'Address'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            width: 80,
                                            dataIndex: 'data_change',
                                            menuDisabled: true,
                                            text: 'Дата',
                                            format: 'd-m-y'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                                metaData.style = 'white-space:pre-wrap;';
                                                return value;

                                            },
                                            width: 337,
                                            dataIndex: 'what_change',
                                            menuDisabled: true,
                                            text: 'Опис змін',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: 83,
                                            dataIndex: 'operator',
                                            menuDisabled: true,
                                            text: 'Оператор'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textareafield',
                                    x: 5,
                                    y: 405,
                                    height: 175,
                                    style: 'background-color: #f3f3f3;',
                                    width: 455,
                                    fieldLabel: 'Останні зміни по квартирі',
                                    labelAlign: 'top',
                                    labelWidth: 120,
                                    name: 'info',
                                    grow: true
                                },
                                {
                                    xtype: 'textareafield',
                                    x: 15,
                                    y: 195,
                                    height: 92,
                                    hidden: true,
                                    width: 300,
                                    fieldLabel: 'Последние изменения по квартире',
                                    labelAlign: 'top',
                                    labelWidth: 120,
                                    name: 'what_change'
                                },
                                {
                                    xtype: 'datefield',
                                    x: 315,
                                    y: 330,
                                    hidden: true,
                                    width: 125,
                                    fieldLabel: 'Дата изменений',
                                    labelAlign: 'top',
                                    name: 'chdata',
                                    format: 'd-m-Y',
                                    submitFormat: 'Y-m-d'
                                },
                                {
                                    xtype: 'fieldset',
                                    x: 5,
                                    y: 5,
                                    height: 65,
                                    style: 'background-color: #F1EEEE;',
                                    width: 965,
                                    layout: 'absolute',
                                    title: 'Площа квартири (м2)',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            x: 5,
                                            y: 5,
                                            width: 130,
                                            fieldLabel: 'Корисна',
                                            labelSeparator: ' ',
                                            labelWidth: 65,
                                            name: 'area_full',
                                            editable: false,
                                            hideTrigger: true,
                                            autoStripChars: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            x: 170,
                                            y: 5,
                                            width: 125,
                                            fieldLabel: 'Житлова',
                                            labelSeparator: ' ',
                                            labelWidth: 60,
                                            name: 'area_life',
                                            editable: false,
                                            hideTrigger: true,
                                            autoStripChars: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            x: 335,
                                            y: 5,
                                            width: 130,
                                            fieldLabel: 'Додаткова',
                                            labelSeparator: ' ',
                                            labelWidth: 70,
                                            name: 'area_dop',
                                            editable: false,
                                            hideTrigger: true,
                                            autoStripChars: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            x: 500,
                                            y: 5,
                                            width: 125,
                                            fieldLabel: 'Балкон',
                                            labelSeparator: ' ',
                                            labelWidth: 50,
                                            name: 'area_balk',
                                            editable: false,
                                            hideTrigger: true,
                                            autoStripChars: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            x: 660,
                                            y: 5,
                                            width: 120,
                                            fieldLabel: 'Кімнат',
                                            labelSeparator: ' ',
                                            labelWidth: 55,
                                            name: 'room',
                                            editable: false,
                                            hideTrigger: true,
                                            allowDecimals: false,
                                            autoStripChars: true,
                                            decimalPrecision: 0
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            x: 820,
                                            y: 5,
                                            fieldLabel: 'Ліфт',
                                            labelWidth: 40,
                                            name: 'lift',
                                            boxLabel: 'Ні',
                                            inputValue: 'да',
                                            uncheckedValue: 'нет',
                                            listeners: {
                                                change: 'onCheckboxfieldChange'
                                            }
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'house_id'
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'operator'
                        }
                    ]
                }
            ]
        }
    ]

});