/*
 * File: app/view/flat/tabAppBtiViewModel.js
 * Date: Wed Jul 29 2020 15:04:41 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.view.flat.tabAppBtiViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.tabappbti'

});