/*
 * File: app/view/flat/TabAppTeplomerViewController.js
 * Date: Tue Dec 22 2020 15:45:08 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.view.flat.TabAppTeplomerViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tabappteplomer',

    onGrAppTeplomerSelect: function(rowmodel, record, index, eOpts) {
        var stUser = Ext.data.StoreManager.get("StUser");
        var stTekPokTeplomera = Ext.data.StoreManager.get("StTekPokTeplomera");
        var stAllPokTeplomera = Ext.data.StoreManager.get("StAllPokTeplomera");

        var values =stUser.getAt(0);
        var login = values.get('login');
        var password = values.get('password');
        var address_id = values.get('address_id');
        var house_id = values.get('house_id');

        var fmTeplomer = Ext.getCmp('fmAppTeplomer');
        var dt = new Date();
        var d = Ext.Date.getDaysInMonth(dt);
        fmTeplomer.getForm().findField('date_new').setValue(Ext.Date.format(dt, 'Y-m-d'));

        if (record){
            fmTeplomer.getForm().findField('fmAppTeplomer_id').setValue(record.data.teplomer_id);
            var insTekPokAppTeplomer = fmTeplomer.down('#insTekPokAppTeplomer');

            var newValue = fmTeplomer.getForm().findField('newValue');
            fmTeplomer.getForm().findField('pok_id').setValue(record.data.pok_id);

            var newKubov = fmTeplomer.getForm().findField('newKubov');


            stTekPokTeplomera.load({
                params: {
                    login:login,
                    password:password,
                    address_id: address_id,
                    what:'TekPokTeplomera',
                    what_id: record.data.teplomer_id,
                    teplomer_id: record.data.teplomer_id,
                    nomer: record.data.nomer
                },
                callback: function(records,operation,success){
                    if(success && records.length){
                        fmTeplomer.getForm().loadRecord(records[0]);

                    }
                },
                scope:this
            });



            stAllPokTeplomera.load({
                params: {
                    login:login,
                    password:password,
                    address_id: address_id,
                    what:'AllPokTeplomera',
                    what_id: record.data.teplomer_id,
                    teplomer_id: record.data.teplomer_id,
                    nomer: record.data.nomer
                },
                scope:this
            });



            insTekPokAppTeplomer.setDisabled(false);

            newValue.setDisabled(false);
        }



    }

});
