/*
 * File: app/view/flat/TabKassa.js
 * Date: Mon Feb 15 2021 10:55:03 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.view.flat.TabKassa', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabkassa',

    requires: [
        'yis.view.flat.TabKassaViewModel',
        'yis.view.NumberFieldDolg',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Number',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.form.field.Date',
        'Ext.form.field.Hidden',
        'Ext.form.field.Display',
        'Ext.grid.column.Date'
    ],

    viewModel: {
        type: 'tabkassa'
    },
    border: false,
    hidden: true,
    id: 'tabKassa',
    scrollable: true,
    width: 847,
    icon: 'resources/css/images/btn64/visa-straight-32px.png',
    title: 'iIPay.ua',
    defaultListenerScope: true,

    layout: {
        type: 'vbox',
        align: 'stretchmax'
    },
    items: [
        {
            xtype: 'container',
            border: false,
            height: 65,
            html: '<h3 class="visa"><span><font style="color:red;">Внимание !!!</font> Оплата производится платежными картами VISA и MasterCard выданными в Украине.<br> C Вас будет снята коммиссия, установленая cервисом онлайн платежей iPay.ua</span></h3>',
            margin: 5,
            width: 767
        },
        {
            xtype: 'container',
            border: false,
            height: 689,
            margin: 5,
            width: 807,
            layout: {
                type: 'hbox',
                align: 'stretch'
            },
            items: [
                {
                    xtype: 'form',
                    border: false,
                    height: 657,
                    id: 'fmTekNachKassa',
                    margin: 5,
                    width: 522,
                    bodyBorder: true,
                    title: '',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 148,
                            style: 'background-color: #f1eeee;',
                            width: 835,
                            layout: 'absolute',
                            title: 'КП Водоснабжение и канализация',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    x: 245,
                                    y: 5,
                                    disabled: true,
                                    width: 80,
                                    labelStyle: 'font-weight:bold;',
                                    name: 'cbNext1',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCbNext1Change'
                                    }
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 245,
                                    y: 40,
                                    disabled: true,
                                    width: 80,
                                    labelStyle: 'font-weight:bold;',
                                    name: 'cbNext2',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCbNext2Change'
                                    }
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    disabled: true,
                                    width: 110,
                                    name: 'oplata1',
                                    allowBlank: false,
                                    minText: '0',
                                    negativeText: 'Ошибка, сумма меньше нуля',
                                    x: 340,
                                    y: 5,
                                    listeners: {
                                        change: 'onNumberfield1Change'
                                    }
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    disabled: true,
                                    width: 110,
                                    name: 'oplata2',
                                    minValue: 0,
                                    negativeText: 'Ошибка, сумма меньше нуля',
                                    x: 340,
                                    y: 40,
                                    listeners: {
                                        change: 'onNumberfield2Change'
                                    }
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    width: 220,
                                    fieldLabel: 'Вода',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    labelWidth: 120,
                                    name: 'dolg1',
                                    readOnly: true,
                                    x: 10,
                                    y: 5
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    width: 220,
                                    fieldLabel: 'Стоки',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    labelWidth: 120,
                                    name: 'dolg2',
                                    readOnly: true,
                                    x: 10,
                                    y: 40
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    width: 220,
                                    fieldLabel: 'долг по КП МЖКЦ',
                                    labelStyle: 'font-size:9pt;font-weight:bold;',
                                    labelWidth: 120,
                                    name: 'dolg8',
                                    fieldStyle: 'font-size:10pt;font-weight:bold;text-align:right;',
                                    readOnly: true,
                                    x: 10,
                                    y: 75
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 149,
                            style: 'background-color: #f1eeee;',
                            layout: 'absolute',
                            title: 'КП тс Южтеплокоммунэнерго',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    x: 245,
                                    y: 5,
                                    disabled: true,
                                    width: 80,
                                    labelStyle: 'font-weight:bold;',
                                    name: 'cbNext3',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCbNext3Change'
                                    }
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 245,
                                    y: 40,
                                    disabled: true,
                                    width: 80,
                                    labelStyle: 'font-weight:bold;',
                                    name: 'cbNext4',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCbNext4Change'
                                    }
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 245,
                                    y: 75,
                                    disabled: true,
                                    width: 80,
                                    labelStyle: 'font-weight:bold;',
                                    name: 'cbNext7',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCbNext7Change'
                                    }
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    disabled: true,
                                    width: 110,
                                    name: 'oplata3',
                                    minValue: 0,
                                    negativeText: 'Ошибка, сумма меньше нуля',
                                    x: 340,
                                    y: 5,
                                    listeners: {
                                        change: 'onNumberfield3Change'
                                    }
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    disabled: true,
                                    width: 110,
                                    name: 'oplata4',
                                    minValue: 0,
                                    negativeText: 'Ошибка, сумма меньше нуля',
                                    x: 340,
                                    y: 40,
                                    listeners: {
                                        change: 'onNumberfield4Change'
                                    }
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    disabled: true,
                                    width: 110,
                                    name: 'oplata7',
                                    minValue: 0,
                                    negativeText: 'Ошибка, сумма меньше нуля',
                                    x: 340,
                                    y: 75,
                                    listeners: {
                                        change: 'onNumberfield7Change'
                                    }
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    width: 220,
                                    fieldLabel: 'Подогрев',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    labelWidth: 120,
                                    name: 'dolg3',
                                    readOnly: true,
                                    x: 10,
                                    y: 5
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    width: 220,
                                    fieldLabel: 'Отопление',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    labelWidth: 120,
                                    name: 'dolg4',
                                    readOnly: true,
                                    x: 10,
                                    y: 40
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    width: 220,
                                    fieldLabel: 'ПТН',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    labelWidth: 120,
                                    name: 'dolg7',
                                    readOnly: true,
                                    x: 10,
                                    y: 75
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 115,
                            id: 'fsOsmd',
                            style: 'background-color: #f1eeee;',
                            layout: 'absolute',
                            title: 'ОСМД',
                            items: [
                                {
                                    xtype: 'numberFieldDolg',
                                    width: 220,
                                    fieldLabel: 'Квартплата',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    labelWidth: 120,
                                    name: 'dolg5',
                                    readOnly: true,
                                    x: 10,
                                    y: 5
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 245,
                                    y: 5,
                                    disabled: true,
                                    width: 80,
                                    labelStyle: 'font-weight:bold;',
                                    name: 'cbNext5',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCbNext5Change'
                                    }
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    disabled: true,
                                    width: 110,
                                    name: 'oplata5',
                                    minValue: 0,
                                    negativeText: 'Ошибка, сумма меньше нуля',
                                    x: 340,
                                    y: 5,
                                    listeners: {
                                        change: 'onNumberfield5Change'
                                    }
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    width: 220,
                                    fieldLabel: 'долг по Добробут',
                                    labelStyle: 'font-size:9pt;font-weight:bold;',
                                    labelWidth: 120,
                                    name: 'dolg9',
                                    fieldStyle: 'font-size:10pt;font-weight:bold;text-align:right;',
                                    readOnly: true,
                                    x: 10,
                                    y: 40
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 86,
                            style: 'background-color: #f1eeee;',
                            layout: 'absolute',
                            title: 'КП ЮЖТРАНС',
                            items: [
                                {
                                    xtype: 'numberFieldDolg',
                                    width: 220,
                                    fieldLabel: 'Вывоз ТБО',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    labelWidth: 120,
                                    name: 'dolg6',
                                    readOnly: true,
                                    x: 10,
                                    y: 5
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 245,
                                    y: 5,
                                    disabled: true,
                                    width: 80,
                                    labelStyle: 'font-weight:bold;',
                                    name: 'cbNext6',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCbNext6Change'
                                    }
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    disabled: true,
                                    width: 110,
                                    name: 'oplata6',
                                    minValue: 0,
                                    negativeText: 'Ошибка, сумма меньше нуля',
                                    x: 340,
                                    y: 5,
                                    listeners: {
                                        change: 'onNumberfield6Change'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 131,
                            style: 'background-color: #f1eeee;',
                            width: 474,
                            layout: 'absolute',
                            title: 'Долг на текущий месяц по коммунальным услугам',
                            items: [
                                {
                                    xtype: 'button',
                                    x: 0,
                                    y: 50,
                                    id: 'DoAllReset',
                                    width: 100,
                                    icon: 'resources/css/images/ico/xsldbg_refresh.png',
                                    text: 'Сброс',
                                    textAlign: 'left',
                                    tooltip: 'Очистить все выбранное',
                                    listeners: {
                                        click: 'onDoAllResetClick'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    x: 110,
                                    y: 50,
                                    formBind: true,
                                    id: 'account',
                                    width: 130,
                                    icon: 'resources/css/images/ico/schet.png',
                                    text: 'Просчитать',
                                    tooltip: 'Пересчитать все суммы к оплате',
                                    listeners: {
                                        click: 'onAccountClick'
                                    }
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 245,
                                    y: 5,
                                    hidden: true,
                                    fieldLabel: '',
                                    name: 'cbNext',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCbNextChange'
                                    }
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    id: 'newOplataKassa',
                                    width: 200,
                                    fieldLabel: 'К оплате',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    labelWidth: 80,
                                    name: 'newOplata',
                                    fieldStyle: 'color:red;font-size:12pt;font-weight:bold;text-align:right;',
                                    readOnly: true,
                                    minValue: 0.01,
                                    negativeText: 'Значение должно быть больше 0',
                                    x: 255,
                                    y: 5,
                                    listeners: {
                                        validitychange: 'onNumberfieldValidityChange1'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: 10,
                                    y: 5,
                                    width: 220,
                                    fieldLabel: 'Долг',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    labelWidth: 120,
                                    name: 'dolg',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    readOnly: true
                                },
                                {
                                    xtype: 'button',
                                    x: 250,
                                    y: 50,
                                    formBind: true,
                                    shadowOffset: 2,
                                    border: '2px',
                                    disabled: true,
                                    id: 'insTekPokKassa',
                                    width: 250,
                                    icon: 'resources/css/images/btn64/visa-straight-32px.png',
                                    text: 'Начать процедуру оплаты'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'form',
                    border: false,
                    height: 500,
                    id: 'fmInfoApp1',
                    margin: '15 5 0 5',
                    width: 267,
                    collapseFirst: false,
                    title: '',
                    items: [
                        {
                            xtype: 'gridpanel',
                            height: 257,
                            id: 'grAppVodomerKassa',
                            scrollable: true,
                            width: 266,
                            title: 'Ввод новых показаний ',
                            emptyText: 'Нет счетчиков',
                            store: 'StVodomerKassa',
                            viewConfig: {
                                height: 170,
                                style: 'font-size:9px;',
                                emptyText: 'Счетчиков нет'
                            },
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'vodomer_id',
                                    text: 'водомер_ид',
                                    format: '0'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'address_id',
                                    text: 'Address_id',
                                    format: '0'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'raion',
                                    text: 'House_id'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'period',
                                    text: 'Address'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        metaData.style = 'color:#D10000;font-weight:bold;';
                                        var retValue = '';
                                        switch (value) {
                                            case 'Хвода':
                                            retValue ='<span><img clas="icon" src="resources/css/images/ico/pipex.png"/></span>';
                                            break;
                                            case 'Гвода':
                                            retValue ='<span><img clas="icon" src="resources/css/images/ico/pipeg.png"/></span>';
                                        }
                                        return retValue;
                                    },
                                    width: 80,
                                    dataIndex: 'voda',
                                    menuDisabled: true,
                                    text: 'вода'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 90,
                                    dataIndex: 'place',
                                    menuDisabled: true,
                                    text: 'место'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 77,
                                    dataIndex: 'nomer',
                                    menuDisabled: true,
                                    text: 'номер',
                                    format: '0'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 288,
                            style: 'background-color: #f1eeee;',
                            width: 263,
                            title: 'Последние показания',
                            items: [
                                {
                                    xtype: 'button',
                                    anchor: '100%',
                                    disabled: true,
                                    height: 25,
                                    id: 'delTekPokVodKassa',
                                    margin: 5,
                                    width: 190,
                                    icon: 'resources/css/images/ico/s_error.png',
                                    text: 'Удалить показание',
                                    tooltip: 'Удалить текущее показание водомера'
                                },
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    margin: 5,
                                    width: 190,
                                    fieldLabel: 'Дата показ',
                                    labelWidth: 85,
                                    name: 'fdate',
                                    fieldStyle: 'font-size:11pt;font-weight:bold;text-align:right;',
                                    readOnly: true,
                                    altFormats: 'd-m-Y|m/d/Y|n/j/Y|n/j/y|m/j/y|n/d/y|m/j/Y|n/d/Y|m-d-y|m-d-Y|m/d|m-d|md|mdy|mdY|d|Y-m-d|n-j|n/j',
                                    format: 'd-m-Y'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    margin: 5,
                                    width: 190,
                                    fieldLabel: 'предыдущее',
                                    labelWidth: 85,
                                    name: 'pred',
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    margin: 5,
                                    width: 190,
                                    fieldLabel: 'кол-во кубов',
                                    labelWidth: 85,
                                    name: 'kub',
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    margin: 5,
                                    width: 190,
                                    fieldLabel: 'текущее',
                                    labelWidth: 85,
                                    name: 'tek',
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    readOnly: true
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    shadowOffset: 1,
                                    disabled: true,
                                    id: 'newValueVodomer',
                                    margin: 5,
                                    width: 190,
                                    fieldLabel: 'новое показ',
                                    labelWidth: 85,
                                    name: 'newValue',
                                    value: 0,
                                    fieldStyle: 'color:red;font-size:12pt;font-weight:bold;text-align:right;',
                                    allowBlank: false,
                                    hideTrigger: true,
                                    selectOnFocus: true,
                                    allowDecimals: false,
                                    autoStripChars: true,
                                    decimalPrecision: 0,
                                    minValue: 0,
                                    negativeText: 'Значение должно быть больше 1',
                                    listeners: {
                                        validitychange: 'onNewValueVodomerValidityChange'
                                    }
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var me = this;
                                        //console.log(me);
                                        //STORE
                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var stTekNachKassa = Ext.data.StoreManager.get("StTekNachKassa");
                                        var stTekPokVodomera = Ext.data.StoreManager.get("StTekPokVodomera");//QueryVodomer.getResults <TekPokVodomera>
                                        //LOGIN & PASSWORD
                                        var values =stUser.getAt(0);
                                        var params = {
                                            user_id:values.get('user_id'),
                                            login:values.get('login'),
                                            address_id:values.get('address_id'),
                                            raion_id:values.get('raion_id'),
                                            what:'AVodomer'

                                        };
                                        //console.log(values);
                                        //FORMA
                                        var fmTekNachKassa = Ext.getCmp('fmTekNachKassa');
                                        var fmInfoApp = Ext.getCmp('fmInfoApp1');
                                        var value = fmInfoApp.getValues();

                                        //LOGIKA

                                        Ext.Object.merge(value, params);
                                        var newValue = value.newValue;
                                        var max =newValue - value.tek;
                                        if (max<=0){
                                            Ext.MessageBox.show({
                                                title: 'Проверка вводимых данных',
                                                msg: 'Текущие показания <b>'+value.tek+'</b><br>Новые показания <b>'+newValue+'</b><br>Введите правильные показания !.',
                                                buttons: Ext.MessageBox.CANCEL,
                                                icon: Ext.MessageBox.ERROR,
                                                buttonText:
                                                {
                                                    cancel:'отмена'
                                                },
                                                fn:function(btn,newValue){
                                                    if(btn=='cancel'){
                                                        fmInfoApp.getForm().findField('newValue').focus();
                                                        return false;
                                                    }
                                                }
                                            });
                                        } else if(max > 20) {
                                            Ext.MessageBox.confirm({
                                                title: 'Проверка вводимых данных',
                                                msg: 'Вводимые показания <b>'+newValue+'</b> очень большие <b>'+ max +'</b> куб(a)<br>Подтвердите или отмените вводимые показания.',
                                                buttons: Ext.MessageBox.OKCANCEL,
                                                icon: Ext.MessageBox.ERROR,
                                                buttonText:{
                                                    ok:'подтвеждаю',
                                                    cancel:'отмена'
                                                },
                                                fn:function(btn,newValue){
                                                    if(btn=='cancel'){
                                                        fmInfoApp.getForm().findField('newValue').focus();
                                                        return false;
                                                    }else{
                                                        QueryVodomer.newPokVodomera(value,function(results){
                                                            if (results.success === "1"){

                                                                stTekNachKassa.load({
                                                                    params: {
                                                                        login:value.login,
                                                                        what_id: value.address_id,
                                                                        address_id: value.address_id,
                                                                        raion_id: value.raion_id,
                                                                        what:'TekNachAllAppBank'
                                                                    },
                                                                    callback: function(rec,operation,succ){
                                                                        if(succ){
                                                                            fmTekNachKassa.getForm().loadRecord(rec[0]);
                                                                        }
                                                                    },
                                                                    scope:this
                                                                });

                                                                stTekPokVodomera.load({
                                                                    params: {
                                                                        what:'TekPokVodomera',
                                                                        what_id: value.address_id,
                                                                        address_id: value.address_id,
                                                                        vodomer_id: value.vodomer_id,
                                                                        login:value.login
                                                                    },
                                                                    callback: function(records,operation,success){
                                                                        if(success){
                                                                            fmInfoApp.getForm().findField('tek').setValue(records[0].get('tek'));
                                                                            fmInfoApp.getForm().findField('pred').setValue(records[0].get('pred'));
                                                                            fmInfoApp.getForm().findField('kub').setValue(records[0].get('kub'));
                                                                            fmInfoApp.getForm().findField('fdate').setValue(records[0].get('data'));
                                                                            fmInfoApp.getForm().findField('pok_id').setValue(records[0].get('pok_id'));
                                                                            fmInfoApp.getForm().findField('type').setValue(records[0].get('type'));
                                                                            fmInfoApp.getForm().findField('vodomer_id').setValue(records[0].get('vodomer_id'));
                                                                            fmInfoApp.getForm().findField('place').setValue(records[0].get('place'));
                                                                        }
                                                                    },
                                                                    scope:this
                                                                });
                                                                Ext.MessageBox.show({title: 'Ввод текущих показаний водомера ',
                                                                    msg: results.msg,
                                                                    buttons: Ext.MessageBox.OK,
                                                                    icon: Ext.MessageBox.INFO
                                                                });
                                                                fmInfoApp.getForm().findField('newValue').setValue(0).focus();


                                                            }else{
                                                                Ext.MessageBox.show({title: 'Ввод текущих показаний водомера',
                                                                    msg: results.msg,
                                                                    buttons: Ext.MessageBox.OK,
                                                                    icon: Ext.MessageBox.ERROR
                                                                });
                                                                fmInfoApp.getForm().findField('newValue').setValue(0).focus();

                                                            }
                                                        });
                                                    }
                                                }
                                            });


                                        } else {
                                            QueryVodomer.newPokVodomera(value,function(results){
                                                if (results.success==='1'){
                                                    stTekNachKassa.load({
                                                        params: {
                                                            login:value.login,
                                                            password:value.password,
                                                            what_id: value.address_id,
                                                            address_id: value.address_id,
                                                            raion_id: value.raion_id,
                                                            what:'TekNachAllAppBank'
                                                        },
                                                        callback: function(rec,operation,succ){
                                                            if(succ){
                                                                //   console.log(rec);

                                                                fmTekNachKassa.getForm().loadRecord(rec[0]);
                                                            }
                                                        },
                                                        scope:this
                                                    });

                                                    stTekPokVodomera.load({
                                                        params: {
                                                            what:'TekPokVodomera',
                                                            what_id: value.address_id,
                                                            address_id: value.address_id,
                                                            vodomer_id: value.vodomer_id,
                                                            login:value.login,
                                                            password:value.password
                                                        },
                                                        callback: function(records,operation,success){
                                                            if(success){
                                                                //console.log(records);

                                                                fmInfoApp.getForm().findField('tek').setValue(records[0].get('tek'));
                                                                fmInfoApp.getForm().findField('pred').setValue(records[0].get('pred'));
                                                                fmInfoApp.getForm().findField('kub').setValue(records[0].get('kub'));
                                                                fmInfoApp.getForm().findField('fdate').setValue(records[0].get('data'));
                                                                fmInfoApp.getForm().findField('pok_id').setValue(records[0].get('pok_id'));
                                                                fmInfoApp.getForm().findField('type').setValue(records[0].get('type'));
                                                                fmInfoApp.getForm().findField('place').setValue(records[0].get('place'));
                                                                fmInfoApp.getForm().findField('vodomer_id').setValue(records[0].get('vodomer_id'));
                                                            }
                                                        },
                                                        scope:this
                                                    });
                                                    Ext.MessageBox.show({title: 'Ввод текущих показаний водомера ',
                                                        msg: results.msg,
                                                        buttons: Ext.MessageBox.OK,
                                                        icon: Ext.MessageBox.INFO
                                                    });
                                                    fmInfoApp.getForm().findField('newValue').setValue(0).focus();

                                                }else{
                                                    Ext.MessageBox.show({title: 'Ввод текущих показаний водомера ',
                                                        msg: results.msg,
                                                        buttons: Ext.MessageBox.OK,
                                                        icon: Ext.MessageBox.ERROR
                                                    });
                                                    fmInfoApp.getForm().findField('newValue').setValue(0).focus();

                                                }
                                            });
                                        }

                                    },
                                    anchor: '100%',
                                    shadowOffset: 2,
                                    border: '2px',
                                    disabled: true,
                                    id: 'insTekPokVodKassa',
                                    margin: 5,
                                    width: 190,
                                    icon: 'resources/css/images/ico/yes22.png',
                                    text: 'Записать показание'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    width: 145,
                                    fieldLabel: 'показ',
                                    labelWidth: 55,
                                    name: 'pok_id'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    fieldLabel: 'Label',
                                    name: 'place'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    fieldLabel: 'Label',
                                    name: 'vodomer_id'
                                },
                                {
                                    xtype: 'hiddenfield',
                                    fieldLabel: 'Label',
                                    name: 'type'
                                },
                                {
                                    xtype: 'textfield',
                                    hidden: true,
                                    width: 70,
                                    fieldLabel: '',
                                    labelPad: 15,
                                    labelSeparator: ' ',
                                    labelWidth: 20,
                                    name: 'address_id'
                                },
                                {
                                    xtype: 'displayfield',
                                    hidden: true,
                                    width: 305,
                                    fieldLabel: 'Адрес',
                                    labelSeparator: ' ',
                                    labelStyle: '',
                                    labelWidth: 50,
                                    name: 'address'
                                },
                                {
                                    xtype: 'displayfield',
                                    hidden: true,
                                    width: 385,
                                    fieldLabel: '',
                                    labelSeparator: ' ',
                                    labelStyle: '',
                                    labelWidth: 50,
                                    name: 'nanim',
                                    fieldStyle: 'color: #D15706; text-shadow: -1px -1px white, 1px 1px #333;font-size:14pt;text-align:left;'
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            margin: 5,
            width: 818,
            animCollapse: true,
            collapsible: true,
            title: 'Последние платежи',
            titleCollapse: true,
            emptyText: 'нет данных о платежах',
            store: 'StTekOplata',
            viewConfig: {
                emptyText: 'Нет данных по оплате'
            },
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'rec_id',
                    format: '0'
                },
                {
                    xtype: 'datecolumn',
                    width: 75,
                    dataIndex: 'data',
                    menuDisabled: true,
                    text: 'Дата',
                    format: 'd-m-y'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    align: 'right',
                    dataIndex: 'kvartplata',
                    menuDisabled: true,
                    text: 'Кварт',
                    format: '0.00'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    align: 'right',
                    dataIndex: 'otoplenie',
                    menuDisabled: true,
                    text: 'Отопл',
                    format: '0.00'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    align: 'right',
                    dataIndex: 'ptn',
                    menuDisabled: true,
                    text: 'ПТН',
                    format: '0.00'
                },
                {
                    xtype: 'numbercolumn',
                    width: 62,
                    align: 'right',
                    dataIndex: 'podogrev',
                    menuDisabled: true,
                    text: 'Подог',
                    format: '0.00'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    align: 'right',
                    dataIndex: 'voda',
                    menuDisabled: true,
                    text: 'Вода',
                    format: '0.00'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    align: 'right',
                    dataIndex: 'stoki',
                    menuDisabled: true,
                    text: 'Стоки',
                    format: '0.00'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    align: 'right',
                    dataIndex: 'tbo',
                    menuDisabled: true,
                    text: 'ТБО',
                    format: '0.00'
                },
                {
                    xtype: 'numbercolumn',
                    width: 80,
                    align: 'right',
                    dataIndex: 'summa',
                    menuDisabled: true,
                    text: 'Сумма',
                    format: '0.00'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    width: 90,
                    dataIndex: 'kassa',
                    text: 'Касса'
                },
                {
                    xtype: 'gridcolumn',
                    width: 95,
                    dataIndex: 'prixod',
                    menuDisabled: true,
                    text: 'Приход'
                },
                {
                    xtype: 'gridcolumn',
                    width: 81,
                    dataIndex: 'operator',
                    text: 'Оператор',
                    flex: 1
                }
            ]
        }
    ],

    onCbNext1Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg1').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata1').getValue();

        form.down('#DoAllReset').setDisabled(false);
        if (form.getForm().findField('cbNext1').getValue() === true){
            form.getForm().findField('oplata1').setDisabled(false);
        } else {
            form.getForm().findField('oplata1').setDisabled(true);
        }
        if (newValue) {
            //console.log(newValue);
            if(dolg > 0) {
                form.getForm().findField('oplata1').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('oplata1').setValue(0);
                form.getForm().findField('cbNext1').setValue(false);
                form.getForm().findField('cbNext1').setDisabled(true);
                form.getForm().findField('oplata1').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg1').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {
            form.getForm().findField('oplata1').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata1').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg1').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onCbNext2Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg2').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata2').getValue();

        form.down('#DoAllReset').setDisabled(false);
        if (form.getForm().findField('cbNext2').getValue() === true){
            form.getForm().findField('oplata2').setDisabled(false);
        } else {
            form.getForm().findField('oplata2').setDisabled(true);
        }
        if (newValue) {
            //   console.log(newValue);
            if(dolg > 0) {
                form.getForm().findField('oplata2').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('oplata2').setValue(0);
                form.getForm().findField('cbNext2').setValue(false);
                form.getForm().findField('cbNext2').setDisabled(true);
                form.getForm().findField('oplata2').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg2').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {
            form.getForm().findField('oplata2').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata2').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg2').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onNumberfield1Change: function(field, newValue, oldValue, eOpts) {
        if (newValue !== oldValue){
            //  console.log(newValue);
            var form = field.findParentByType('form');
            var oplata = 0;
            var oplata2 = form.getForm().findField('oplata2').getValue();
            var oplata3 = form.getForm().findField('oplata3').getValue();
            var oplata4 = form.getForm().findField('oplata4').getValue();
            var oplata5 = form.getForm().findField('oplata5').getValue();
            var oplata6 = form.getForm().findField('oplata6').getValue();
            var oplata7 = form.getForm().findField('oplata7').getValue();

            form.getForm().findField('oplata1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg1').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');
            form.down('#account').setDisabled(false);
            form.down('#DoAllReset').setDisabled(false);

             oplata = newValue + oplata2 + oplata3 + oplata4 + oplata5 + oplata6 + oplata7 ;

            var newOplata = form.getForm().findField('newOplata').setValue(oplata);

        }
    },

    onNumberfield2Change: function(field, newValue, oldValue, eOpts) {
        if (newValue !== oldValue){
            // console.log(newValue);
            var form = field.findParentByType('form');

            var oplata = 0;
            var oplata1 = form.getForm().findField('oplata1').getValue();
            var oplata3 = form.getForm().findField('oplata3').getValue();
            var oplata4 = form.getForm().findField('oplata4').getValue();
            var oplata5 = form.getForm().findField('oplata5').getValue();
            var oplata6 = form.getForm().findField('oplata6').getValue();
            var oplata7 = form.getForm().findField('oplata7').getValue();

            form.getForm().findField('oplata2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg2').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');

            oplata = newValue + oplata1 + oplata3 + oplata4 + oplata5 + oplata6 + oplata7;

            form.getForm().findField('newOplata').setValue(oplata);
            form.down('#account').setDisabled(false);
            form.down('#DoAllReset').setDisabled(false);



        }
    },

    onCbNext3Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg3').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata3').getValue();

        form.down('#DoAllReset').setDisabled(false);
        if (form.getForm().findField('cbNext3').getValue() === true){
            form.getForm().findField('oplata3').setDisabled(false);
        } else {
            form.getForm().findField('oplata3').setDisabled(true);
        }
        if (newValue) {
            //  console.log(newValue);
            if(dolg > 0) {
                form.getForm().findField('oplata3').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('oplata3').setValue(0);
                form.getForm().findField('cbNext3').setValue(false);
                form.getForm().findField('cbNext3').setDisabled(true);
                form.getForm().findField('oplata3').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg3').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {
            form.getForm().findField('oplata3').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata3').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg3').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onCbNext4Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg4').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata4').getValue();

        form.down('#DoAllReset').setDisabled(false);
        if (form.getForm().findField('cbNext4').getValue() === true){
            form.getForm().findField('oplata4').setDisabled(false);
        } else {
            form.getForm().findField('oplata4').setDisabled(true);
        }
        if (newValue) {
            //   console.log(newValue);
            if(dolg > 0) {
                form.getForm().findField('oplata4').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('oplata4').setValue(0);
                form.getForm().findField('cbNext4').setValue(false);
                form.getForm().findField('cbNext4').setDisabled(true);
                form.getForm().findField('oplata4').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg4').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {
            form.getForm().findField('oplata4').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata4').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg4').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onCbNext7Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg7').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata7').getValue();

        form.down('#DoAllReset').setDisabled(false);
        if (form.getForm().findField('cbNext7').getValue() === true){
            form.getForm().findField('oplata7').setDisabled(false);
        } else {
            form.getForm().findField('oplata7').setDisabled(true);
        }
        if (newValue) {
            //   console.log(newValue);
            if(dolg > 0) {
                form.getForm().findField('oplata7').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('oplata7').setValue(0);
                form.getForm().findField('cbNext7').setValue(false);
                form.getForm().findField('cbNext7').setDisabled(true);
                form.getForm().findField('oplata7').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg7').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {
            form.getForm().findField('oplata7').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata7').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg7').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onNumberfield3Change: function(field, newValue, oldValue, eOpts) {
        if (newValue !== oldValue){
            //   console.log(newValue);
            var form = field.findParentByType('form');
            var oplata = 0;

            var oplata2 = form.getForm().findField('oplata2').getValue();
            var oplata1 = form.getForm().findField('oplata1').getValue();
            var oplata4 = form.getForm().findField('oplata4').getValue();
            var oplata5 = form.getForm().findField('oplata5').getValue();
            var oplata6 = form.getForm().findField('oplata6').getValue();
            var oplata7 = form.getForm().findField('oplata7').getValue();

            form.getForm().findField('oplata3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg3').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');

            oplata = newValue + oplata1 + oplata2 + oplata4 + oplata5 + oplata6+ oplata7;

            var newOplata = form.getForm().findField('newOplata').setValue(oplata);
            form.down('#account').setDisabled(false);
            form.down('#DoAllReset').setDisabled(false);


        }
    },

    onNumberfield4Change: function(field, newValue, oldValue, eOpts) {
        if (newValue !== oldValue){
            //  console.log(newValue);
            var form = field.findParentByType('form');
            var oplata = 0;
            var oplata2 = form.getForm().findField('oplata2').getValue();
            var oplata3 = form.getForm().findField('oplata3').getValue();
            var oplata1 = form.getForm().findField('oplata1').getValue();
            var oplata5 = form.getForm().findField('oplata5').getValue();
            var oplata6 = form.getForm().findField('oplata6').getValue();
            var oplata7 = form.getForm().findField('oplata7').getValue();

            form.getForm().findField('oplata4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg4').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');

                 oplata = newValue + oplata2 + oplata3 + oplata1 + oplata5 + oplata6 + oplata7 ;

            var newOplata = form.getForm().findField('newOplata').setValue(oplata);
            form.down('#account').setDisabled(false);
            form.down('#DoAllReset').setDisabled(false);


        }
    },

    onNumberfield7Change: function(field, newValue, oldValue, eOpts) {
        if (newValue !== oldValue){
            //  console.log(newValue);
            var form = field.findParentByType('form');
            var oplata = 0;
            var oplata2 = form.getForm().findField('oplata2').getValue();
            var oplata3 = form.getForm().findField('oplata3').getValue();
            var oplata4 = form.getForm().findField('oplata4').getValue();
            var oplata5 = form.getForm().findField('oplata5').getValue();
            var oplata6 = form.getForm().findField('oplata6').getValue();
            var oplata1 = form.getForm().findField('oplata1').getValue();

            form.getForm().findField('oplata7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg7').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');

            oplata = newValue + oplata2 + oplata3 + oplata4 + oplata5 + oplata6 + oplata1 ;

            var newOplata = form.getForm().findField('newOplata').setValue(oplata);
            form.down('#account').setDisabled(false);
            form.down('#DoAllReset').setDisabled(false);


        }
    },

    onCbNext5Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg5').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata5').getValue();

        form.down('#DoAllReset').setDisabled(false);
        if (form.getForm().findField('cbNext5').getValue() === true){
            form.getForm().findField('oplata5').setDisabled(false);
        } else {
            form.getForm().findField('oplata5').setDisabled(true);
        }
        if (newValue) {
            //   console.log(newValue);
            if(dolg > 0) {
                form.getForm().findField('oplata5').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('oplata5').setValue(0);
                form.getForm().findField('cbNext5').setValue(false);
                form.getForm().findField('cbNext5').setDisabled(true);
                form.getForm().findField('oplata5').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg5').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {
            form.getForm().findField('oplata5').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata5').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg5').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onNumberfield5Change: function(field, newValue, oldValue, eOpts) {
        if (newValue !== oldValue){
            //  console.log(newValue);
            var form = field.findParentByType('form');
            var oplata = 0;
            var oplata2 = form.getForm().findField('oplata2').getValue();
            var oplata3 = form.getForm().findField('oplata3').getValue();
            var oplata4 = form.getForm().findField('oplata4').getValue();
            var oplata1 = form.getForm().findField('oplata1').getValue();
            var oplata6 = form.getForm().findField('oplata6').getValue();
            var oplata7 = form.getForm().findField('oplata7').getValue();

            form.getForm().findField('oplata5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg5').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');


             oplata = newValue + oplata2 + oplata3 + oplata4 + oplata1 + oplata6 + oplata7 ;

            var newOplata = form.getForm().findField('newOplata').setValue(oplata);
            form.down('#account').setDisabled(false);
            form.down('#DoAllReset').setDisabled(false);


        }
    },

    onCbNext6Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg6').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata6').getValue();

        form.down('#DoAllReset').setDisabled(false);
        if (form.getForm().findField('cbNext6').getValue() === true){
            form.getForm().findField('oplata6').setDisabled(false);
        } else {
            form.getForm().findField('oplata6').setDisabled(true);
        }
        if (newValue) {
            //   console.log(newValue);
            if(dolg > 0) {
                form.getForm().findField('oplata6').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('oplata6').setValue(0);
                form.getForm().findField('cbNext6').setValue(false);
                form.getForm().findField('cbNext6').setDisabled(true);
                form.getForm().findField('oplata6').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg6').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {
            form.getForm().findField('oplata6').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata6').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg6').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onNumberfield6Change: function(field, newValue, oldValue, eOpts) {
        if (newValue !== oldValue){
            //  console.log(newValue);
            var form = field.findParentByType('form');
            var oplata = 0;
            var oplata2 = form.getForm().findField('oplata2').getValue();
            var oplata3 = form.getForm().findField('oplata3').getValue();
            var oplata4 = form.getForm().findField('oplata4').getValue();
            var oplata5 = form.getForm().findField('oplata5').getValue();
            var oplata1 = form.getForm().findField('oplata1').getValue();
            var oplata7 = form.getForm().findField('oplata7').getValue();

            form.getForm().findField('oplata6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg6').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');

            oplata = newValue + oplata2 + oplata3 + oplata4 + oplata5 + oplata1 + oplata7 ;

            var newOplata = form.getForm().findField('newOplata').setValue(oplata);
            form.down('#account').setDisabled(false);
            form.down('#DoAllReset').setDisabled(false);


        }
    },

    onDoAllResetClick: function(button, e, eOpts) {
        var form = button.findParentByType('form');
        var dolg = form.getForm().findField('dolg').getValue();
        var dolg1 = form.getForm().findField('dolg1').getValue();
        var dolg2 = form.getForm().findField('dolg2').getValue();
        var dolg3 = form.getForm().findField('dolg3').getValue();
        var dolg4 = form.getForm().findField('dolg4').getValue();
        var dolg5 = form.getForm().findField('dolg5').getValue();
        var dolg6 = form.getForm().findField('dolg6').getValue();
        var dolg7 = form.getForm().findField('dolg7').getValue();


        form.getForm().findField('cbNext').setValue(false);
        form.getForm().findField('cbNext1').setValue(false);
        form.getForm().findField('oplata1').setValue(0);
        form.getForm().findField('oplata1').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg1').setFieldStyle('background-color: #fff; background-image: none;');

        if(dolg1 > 0){
            form.getForm().findField('cbNext1').setDisabled(false);
        } else {
            form.getForm().findField('cbNext1').setDisabled(true);
        }

        form.getForm().findField('cbNext2').setValue(false);
        form.getForm().findField('oplata2').setValue(0);
        form.getForm().findField('oplata2').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg2').setFieldStyle('background-color: #fff; background-image: none;');

        if(dolg2 > 0){
            form.getForm().findField('cbNext2').setDisabled(false);
        } else {
            form.getForm().findField('cbNext2').setDisabled(true);
        }

        form.getForm().findField('cbNext3').setValue(false);
        form.getForm().findField('oplata3').setValue(0);
        form.getForm().findField('oplata3').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg3').setFieldStyle('background-color: #fff; background-image: none;');

        if(dolg3 > 0){
            form.getForm().findField('cbNext3').setDisabled(false);
        } else {
            form.getForm().findField('cbNext3').setDisabled(true);
        }

        form.getForm().findField('cbNext4').setValue(false);
        form.getForm().findField('oplata4').setValue(0);
        form.getForm().findField('oplata4').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg4').setFieldStyle('background-color: #fff; background-image: none;');

        if(dolg4 > 0){
            form.getForm().findField('cbNext4').setDisabled(false);
        } else {
            form.getForm().findField('cbNext4').setDisabled(true);
        }

        form.getForm().findField('cbNext5').setValue(false);
        form.getForm().findField('oplata5').setValue(0);
        form.getForm().findField('oplata5').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg5').setFieldStyle('background-color: #fff; background-image: none;');

        if(dolg5 > 0){
            form.getForm().findField('cbNext5').setDisabled(false);
        } else {
            form.getForm().findField('cbNext5').setDisabled(true);
        }

        form.getForm().findField('cbNext6').setValue(false);
        form.getForm().findField('oplata6').setValue(0);
        form.getForm().findField('oplata6').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg6').setFieldStyle('background-color: #fff; background-image: none;');

        if(dolg6 > 0){
            form.getForm().findField('cbNext6').setDisabled(false);
        } else {
            form.getForm().findField('cbNext6').setDisabled(true);
        }

        form.getForm().findField('cbNext7').setValue(false);
        form.getForm().findField('oplata7').setValue(0);
        form.getForm().findField('oplata7').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg7').setFieldStyle('background-color: #fff; background-image: none;');

        if(dolg7 > 0){
            form.getForm().findField('cbNext7').setDisabled(false);
        } else {
            form.getForm().findField('cbNext7').setDisabled(true);
        }

        form.getForm().findField('cbNext').setValue(false);
        form.getForm().findField('newOplata').setValue(0);
        form.getForm().findField('newOplata').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');


        form.down('#account').setDisabled(true);
        form.down('#DoAllReset').setDisabled(true);


    },

    onAccountClick: function(button, e, eOpts) {
        var form = button.findParentByType('form');
        var oplata = 0;
        var oplata1 = form.getForm().findField('oplata1').getValue();
        var oplata2 = form.getForm().findField('oplata2').getValue();
        var oplata3 = form.getForm().findField('oplata3').getValue();
        var oplata4 = form.getForm().findField('oplata4').getValue();
        var oplata5 = form.getForm().findField('oplata5').getValue();
        var oplata6 = form.getForm().findField('oplata6').getValue();
        var oplata7 = form.getForm().findField('oplata7').getValue();

        oplata = oplata1 + oplata2 + oplata3 + oplata4 + oplata5 + oplata6+ oplata7;

        var newOplata = form.getForm().findField('newOplata').setValue(oplata);
        Ext.MessageBox.show({title: 'Пересчет сумм для оплаты ',
            msg: 'Пересчет выполнен !!!',
            buttons: Ext.MessageBox.OK,
            icon: Ext.MessageBox.INFO
        });

    },

    onCbNextChange: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg  = form.getForm().findField('dolg').getValue();
        var dolg1 = form.getForm().findField('dolg1').getValue();
        var dolg2 = form.getForm().findField('dolg2').getValue();
        var dolg3 = form.getForm().findField('dolg3').getValue();
        var dolg4 = form.getForm().findField('dolg4').getValue();
        var dolg5 = form.getForm().findField('dolg5').getValue();
        var dolg6 = form.getForm().findField('dolg6').getValue();
        var dolg6 = form.getForm().findField('dolg7').getValue();

        if (newValue) {
            form.down('#account').setDisabled(false);

            if(dolg1 > 0){
                form.getForm().findField('cbNext1').setValue(true);
                form.getForm().findField('oplata1').setValue(dolg1);
                form.getForm().findField('dolg1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            } else {
                form.getForm().findField('cbNext1').setValue(false);
                form.getForm().findField('oplata1').setValue(0);
                form.getForm().findField('cbNext1').setDisabled(true);
                form.getForm().findField('oplata1').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg1').setFieldStyle('background-color: #fff; background-image: none;');
            }
            if(dolg2 > 0){
                form.getForm().findField('cbNext2').setValue(true);
                form.getForm().findField('oplata2').setValue(dolg2);
                form.getForm().findField('dolg2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            } else {
                form.getForm().findField('cbNext2').setValue(false);
                form.getForm().findField('oplata2').setValue(0);
                form.getForm().findField('cbNext2').setDisabled(true);
                form.getForm().findField('oplata2').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg2').setFieldStyle('background-color: #fff; background-image: none;');
            }
            if(dolg3 > 0){
                form.getForm().findField('cbNext3').setValue(true);
                form.getForm().findField('oplata3').setValue(dolg3);
                form.getForm().findField('dolg3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            } else {
                form.getForm().findField('cbNext3').setValue(false);
                form.getForm().findField('oplata3').setValue(0);
                form.getForm().findField('cbNext3').setDisabled(true);
                form.getForm().findField('oplata3').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg3').setFieldStyle('background-color: #fff; background-image: none;');
            }
            if(dolg4 > 0){
                form.getForm().findField('cbNext4').setValue(true);
                form.getForm().findField('oplata4').setValue(dolg4);
                form.getForm().findField('dolg4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            } else {
                form.getForm().findField('cbNext4').setValue(false);
                form.getForm().findField('oplata4').setValue(0);
                form.getForm().findField('cbNext4').setDisabled(true);
                form.getForm().findField('oplata4').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg4').setFieldStyle('background-color: #fff; background-image: none;');
            }

            if(dolg5 > 0){
                form.getForm().findField('cbNext5').setValue(true);
                form.getForm().findField('oplata5').setValue(dolg5);
                form.getForm().findField('dolg5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            } else {
                form.getForm().findField('cbNext5').setValue(false);
                form.getForm().findField('oplata5').setValue(0);
                form.getForm().findField('cbNext5').setDisabled(true);
                form.getForm().findField('oplata5').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg5').setFieldStyle('background-color: #fff; background-image: none;');
            }

            if(dolg6 > 0){
                form.getForm().findField('cbNext6').setValue(true);
                form.getForm().findField('oplata6').setValue(dolg6);
                form.getForm().findField('dolg6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            } else {
                form.getForm().findField('cbNext6').setValue(false);
                form.getForm().findField('oplata6').setValue(0);
                form.getForm().findField('cbNext6').setDisabled(true);
                form.getForm().findField('oplata6').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg6').setFieldStyle('background-color: #fff; background-image: none;');
            }
            if(dolg7 > 0){
                form.getForm().findField('cbNext7').setValue(true);
                form.getForm().findField('oplata7').setValue(dolg6);
                form.getForm().findField('dolg7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            } else {
                form.getForm().findField('cbNext7').setValue(false);
                form.getForm().findField('oplata7').setValue(0);
                form.getForm().findField('cbNext7').setDisabled(true);
                form.getForm().findField('oplata7').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg7').setFieldStyle('background-color: #fff; background-image: none;');
            }

            if(dolg > 0){
                form.getForm().findField('newOplata').setValue(dolg);
                form.getForm().findField('dolg').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            } else {
                form.getForm().findField('cbNext').setValue(false);
                form.getForm().findField('newOplata').setValue(0);
                form.getForm().findField('cbNext').setDisabled(true);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');
            }

        }else {
            form.getForm().findField('cbNext').setValue(false);
            form.getForm().findField('cbNext1').setValue(false);
            form.getForm().findField('cbNext2').setValue(false);
            form.getForm().findField('cbNext3').setValue(false);
            form.getForm().findField('cbNext4').setValue(false);
            form.getForm().findField('cbNext5').setValue(false);
            form.getForm().findField('cbNext6').setValue(false);
            form.getForm().findField('cbNext7').setValue(false);

            form.down('#account').setDisabled(true);


            /*
            form.getForm().findField('oplata1').setValue(0);
            form.getForm().findField('oplata1').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg1').setFieldStyle('background-color: #fff; background-image: none;');

            form.getForm().findField('oplata3').setValue(0);
            form.getForm().findField('oplata3').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg3').setFieldStyle('background-color: #fff; background-image: none;');

            form.getForm().findField('oplata2').setValue(0);
            form.getForm().findField('oplata2').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg2').setFieldStyle('background-color: #fff; background-image: none;');

            form.getForm().findField('oplata4').setValue(0);
            form.getForm().findField('oplata4').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg4').setFieldStyle('background-color: #fff; background-image: none;');

            form.getForm().findField('oplata5').setValue(0);
            form.getForm().findField('oplata5').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg5').setFieldStyle('background-color: #fff; background-image: none;');

            form.getForm().findField('oplata6').setValue(0);
            form.getForm().findField('oplata6').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg6').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('newOplata').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('newOplata').setValue(0);
            */

        }


        form.down('#DoAllReset').setDisabled(false);

    },

    onNumberfieldValidityChange1: function(field, isValid, eOpts) {
        var form = field.findParentByType('form');
        if(isValid){
            form.down('#insTekPokKassa').setDisabled(false);
        } else {
            form.down('#insTekPokKassa').setDisabled(true);
        }
    },

    onNewValueVodomerValidityChange: function(field, isValid, eOpts) {
        var form = field.findParentByType('form');
        if(isValid){
            form.down('#insTekPokVodKassa').setDisabled(false);
        } else {
            form.down('#insTekPokVodKassa').setDisabled(true);
        }
    },

    fmResetMtb: function(fmResetMtb) {
        var form = Ext.getCmp('fmTekNachMtb');
        form.getForm().findField('cbNext').setValue(false);
        form.getForm().findField('cbNext1').setValue(false);
        form.getForm().findField('cbNext2').setValue(false);
        form.getForm().findField('cbNext3').setValue(false);
        form.getForm().findField('cbNext4').setValue(false);
        form.getForm().findField('cbNext5').setValue(false);
        form.getForm().findField('cbNext7').setValue(false);

        form.getForm().findField('cbNext').setDisabled(false);
        form.getForm().findField('cbNext1').setDisabled(false);
        form.getForm().findField('cbNext2').setDisabled(false);
        form.getForm().findField('cbNext3').setDisabled(false);
        form.getForm().findField('cbNext4').setDisabled(false);
        form.getForm().findField('cbNext5').setDisabled(false);
        form.getForm().findField('cbNext7').setDisabled(false);

        form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg1').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg2').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg3').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg4').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg5').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg6').setFieldStyle('background-color: #fff; background-image: none;');
        form.getForm().findField('dolg7').setFieldStyle('background-color: #fff; background-image: none;');

        //form.down('#DoAllReset').setDisabled(true);
        //form.down('#account').setDisabled(true);

        //var newOplata = form.getForm().findField('newOplata').setValue(0);

    }

});