/*
 * File: app/view/flat/TabMarfinBank1.js
 * Date: Fri Feb 12 2021 14:30:00 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('yis.view.flat.TabMarfinBank1', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabMarfinBank1',

    requires: [
        'yis.view.flat.TabMarfinBank1ViewModel',
        'yis.view.NumberFieldDolg',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Hidden',
        'Ext.form.field.Number',
        'Ext.button.Button',
        'Ext.form.field.TextArea',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Action'
    ],

    viewModel: {
        type: 'tabMarfinBank1'
    },
    border: false,
    height: 800,
    id: 'tabMarfinBank1',
    scrollable: true,
    width: 939,
    closeAction: 'hide',
    icon: 'resources/css/images/btn64/mtb16.png',
    iconCls: '',
    title: 'МТБ БАНК',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'container',
            border: false,
            height: 661,
            width: 853,
            layout: {
                type: 'hbox',
                align: 'stretch',
                padding: 10
            },
            items: [
                {
                    xtype: 'form',
                    border: false,
                    height: 667,
                    id: 'fmTekNachMarfin',
                    width: 437,
                    bodyBorder: true,
                    title: '',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldset',
                            height: 75,
                            style: 'background-color: #f1eeee;',
                            width: 450,
                            layout: 'absolute',
                            title: 'Задолженность  на текущий момент  по всем коммунальным услугам',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    x: 210,
                                    disabled: true,
                                    width: 170,
                                    name: 'cbNext',
                                    boxLabel: 'оплатить все услуги',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCheckboxfieldChange'
                                    }
                                },
                                {
                                    xtype: 'textfield',
                                    x: 5,
                                    width: 200,
                                    fieldLabel: 'Всего',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    name: 'dolg',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    readOnly: true,
                                    hideTrigger: true
                                },
                                {
                                    xtype: 'hiddenfield',
                                    name: 'rko'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 110,
                            style: 'background-color: #f1eeee;',
                            width: 400,
                            layout: 'absolute',
                            title: 'КП Водоснабжение и канализация',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    x: 5,
                                    width: 200,
                                    fieldLabel: 'Вода',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    name: 'dolg1',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    readOnly: true,
                                    autoStripChars: true,
                                    decimalSeparator: '.'
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 5,
                                    y: 30,
                                    width: 200,
                                    fieldLabel: 'Стоки',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    name: 'dolg2',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    readOnly: true,
                                    autoStripChars: true,
                                    decimalSeparator: '.'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 210,
                                    disabled: true,
                                    width: 80,
                                    name: 'cbNext1',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCheckboxfieldChange1'
                                    }
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 210,
                                    y: 30,
                                    disabled: true,
                                    width: 80,
                                    labelStyle: 'font-weight:bold;',
                                    name: 'cbNext2',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCheckboxfieldChange2'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 300,
                                    disabled: true,
                                    width: 110,
                                    fieldLabel: '',
                                    name: 'oplata1',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    allowBlank: false,
                                    hideTrigger: true,
                                    vtypeText: 'Ошибка, сумма меньше нуля',
                                    autoStripChars: true,
                                    decimalSeparator: '.',
                                    listeners: {
                                        change: 'onNumberfieldChange1'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 300,
                                    y: 30,
                                    disabled: true,
                                    width: 110,
                                    fieldLabel: '',
                                    name: 'oplata2',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    hideTrigger: true,
                                    autoStripChars: true,
                                    decimalSeparator: '.',
                                    listeners: {
                                        change: 'onNumberfieldChange2'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 135,
                            style: 'background-color: #f1eeee;',
                            layout: 'absolute',
                            title: 'КП тс Южтеплокоммунэнерго',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    x: 210,
                                    disabled: true,
                                    width: 80,
                                    labelStyle: 'font-weight:bold;',
                                    name: 'cbNext3',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCheckboxfieldChange3'
                                    }
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 210,
                                    y: 30,
                                    disabled: true,
                                    labelStyle: 'font-weight:bold;',
                                    labelWidth: 65,
                                    name: 'cbNext4',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCheckboxfieldChange4'
                                    }
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 210,
                                    y: 60,
                                    disabled: true,
                                    labelStyle: 'font-weight:bold;',
                                    labelWidth: 65,
                                    name: 'cbNext7',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCheckboxfieldChange7'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 300,
                                    disabled: true,
                                    width: 110,
                                    fieldLabel: '',
                                    name: 'oplata3',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    hideTrigger: true,
                                    decimalSeparator: '.',
                                    minValue: 0,
                                    negativeText: 'Ошибка, сумма меньше нуля',
                                    listeners: {
                                        change: 'onNumberfieldChange3'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 300,
                                    y: 30,
                                    disabled: true,
                                    width: 110,
                                    fieldLabel: '',
                                    name: 'oplata4',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    hideTrigger: true,
                                    decimalSeparator: '.',
                                    minValue: 0,
                                    negativeText: 'Ошибка, сумма меньше нуля',
                                    listeners: {
                                        change: 'onNumberfieldChange4'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 300,
                                    y: 60,
                                    disabled: true,
                                    width: 110,
                                    fieldLabel: '',
                                    name: 'oplata7',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    hideTrigger: true,
                                    decimalSeparator: '.',
                                    minValue: 0,
                                    negativeText: 'Ошибка, сумма меньше нуля',
                                    listeners: {
                                        change: 'onNumberfieldChange7'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 5,
                                    width: 200,
                                    fieldLabel: 'Подогрев',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    name: 'dolg3',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    readOnly: true,
                                    autoStripChars: true,
                                    decimalSeparator: '.'
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 5,
                                    y: 30,
                                    width: 200,
                                    fieldLabel: 'Отопление',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    name: 'dolg4',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    readOnly: true,
                                    decimalSeparator: '.'
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 5,
                                    y: 60,
                                    width: 200,
                                    fieldLabel: 'ПТН',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    name: 'dolg7',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    readOnly: true,
                                    decimalSeparator: '.'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 75,
                            id: 'fsKvartplata',
                            style: 'background-color: #f1eeee;',
                            layout: 'absolute',
                            title: 'ОСМД',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    x: 210,
                                    disabled: true,
                                    width: 80,
                                    labelStyle: 'font-weight:bold;',
                                    name: 'cbNext5',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCheckboxfieldChange5'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 300,
                                    disabled: true,
                                    width: 110,
                                    fieldLabel: '',
                                    name: 'oplata5',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    hideTrigger: true,
                                    autoStripChars: true,
                                    decimalSeparator: '.',
                                    minValue: 0,
                                    negativeText: 'Ошибка, сумма меньше нуля',
                                    listeners: {
                                        change: 'onNumberfieldChange5'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 5,
                                    width: 200,
                                    fieldLabel: 'Квартплата',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    name: 'dolg5',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    readOnly: true,
                                    decimalSeparator: '.'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 90,
                            style: 'background-color: #f1eeee;',
                            layout: 'absolute',
                            title: 'КП ЮЖТРАНС',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    x: 210,
                                    disabled: true,
                                    width: 80,
                                    labelStyle: 'font-weight:bold;',
                                    name: 'cbNext6',
                                    boxLabel: 'к оплате',
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCheckboxfieldChange6'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 300,
                                    disabled: true,
                                    width: 110,
                                    fieldLabel: '',
                                    name: 'oplata6',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    hideTrigger: true,
                                    decimalSeparator: '.',
                                    minValue: 0,
                                    negativeText: 'Ошибка, сумма меньше нуля',
                                    listeners: {
                                        change: 'onNumberfieldChange6'
                                    }
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 5,
                                    width: 200,
                                    fieldLabel: 'Вывоз ТБО',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    name: 'dolg6',
                                    value: 0,
                                    fieldStyle: 'font-size:12pt;font-weight:bold;text-align:right;',
                                    readOnly: true,
                                    decimalSeparator: '.'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            height: 97,
                            style: 'background-color: #f1eeee;',
                            width: 474,
                            layout: 'absolute',
                            title: '',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    x: 220,
                                    y: 40,
                                    width: 190,
                                    fieldLabel: 'К оплате',
                                    labelStyle: 'font-size:12pt;font-weight:bold;',
                                    labelWidth: 80,
                                    name: 'newOplata',
                                    value: 0,
                                    fieldStyle: 'color:red;font-size:12pt;font-weight:bold;text-align:right;background-color: #FAFAD2;',
                                    readOnly: true,
                                    hideTrigger: true,
                                    decimalSeparator: '.'
                                },
                                {
                                    xtype: 'button',
                                    x: 10,
                                    y: 40,
                                    formBind: true,
                                    shadowOffset: 2,
                                    border: '2px',
                                    disabled: true,
                                    id: 'insOplataMarfinBank',
                                    width: 190,
                                    icon: 'resources/css/images/btn64/mtb16.png',
                                    text: 'Сформировать платеж'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 10,
                                    y: 5,
                                    width: 320,
                                    fieldLabel: 'комиссия за инфоуслуги',
                                    labelWidth: 200,
                                    name: 'cbNext8',
                                    boxLabel: 'согласен',
                                    checked: true,
                                    inputValue: '1',
                                    listeners: {
                                        change: 'onCheckboxfieldChange8'
                                    }
                                },
                                {
                                    xtype: 'numberFieldDolg',
                                    width: 65,
                                    name: 'commission',
                                    value: 3,
                                    fieldStyle: 'background-color: #FAFAD2; background-image: none;font-size:10pt;font-weight:bold;text-align:right;',
                                    maxValue: 3,
                                    minValue: 0,
                                    x: 345,
                                    y: 5
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'container',
                    height: 589,
                    width: 393,
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'container',
                            border: false,
                            height: 428,
                            html: '<h3 class="mtb"><span><font style="color:red;text-align:justify;">Внимание !!!</font> Выберите коммунальные услуги для оплаты с помощью чекбоксов "оплатить все услуги" или "к оплате" или введя непосредственно сумму в поле "к оплате" услуги. Будет сформирована сумма к оплате. К этой сумме будет добавлена комиссия за информационные услуги в размере  3 грн. Вы можете отказаться от комиссии сняв галочку с чекбокса "согласен". Сформировав платёж, Вы получите идентификатор и сумма платежа. Перейдите на <a href="https://i.mtb.ua/web_banking" target="_blank" >СЭП "Интернет-Банкинг" МТБ БАНКА </a> для оплаты ,введите полученный идентификатор и сумму платежа. После завершения всех операций в СЭП «Интернет-Банкинг» вернитесь на сайт и обновите данные о задолженности. Если от банка уже был получен ответ об успешном завершении Платежа, то в таблице "Платежи через СЭП «Интернет-Банкинг» МТБ БАНКА" статус "в обработке" поменяется на "оплачено", рядом появится значок принтера и Вы сможете распечатать платеж. Ответ из банка может быть получен в течении суток.</span></h3>',
                            width: 357,
                            layout: 'fit'
                        },
                        {
                            xtype: 'container',
                            height: 59,
                            layout: 'anchor',
                            items: [
                                {
                                    xtype: 'button',
                                    anchor: '100%',
                                    id: 'checkOplata',
                                    margin: '0 30 0 30',
                                    icon: 'resources/css/images/ico/refresh.png',
                                    scale: 'medium',
                                    text: 'Обновить данные по задолженности',
                                    textAlign: 'left',
                                    tooltip: 'Обновить данные по задолженности'
                                }
                            ]
                        },
                        {
                            xtype: 'form',
                            height: 67,
                            id: 'fmParamsPay',
                            style: 'background-color: #C2D9C9;',
                            width: 354,
                            layout: 'absolute',
                            bodyPadding: 5,
                            title: '',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    x: 20,
                                    y: 0,
                                    width: 160,
                                    fieldLabel: 'Идентификатор платежа',
                                    labelAlign: 'top',
                                    name: 'payment_id',
                                    fieldStyle: 'background-color:#F0F8FF;font-size:14pt;font-weight:bold;text-align:left;color:red;',
                                    readOnly: true,
                                    allowBlank: false,
                                    hideTrigger: true,
                                    decimalPrecision: 0,
                                    decimalSeparator: '.'
                                },
                                {
                                    xtype: 'numberfield',
                                    x: 210,
                                    y: 0,
                                    width: 130,
                                    fieldLabel: 'Сумма платежа',
                                    labelAlign: 'top',
                                    name: 'summa',
                                    fieldStyle: 'background-color:#F0F8FF;font-size:14pt;font-weight:bold;text-align:left;color:red;',
                                    readOnly: true,
                                    allowBlank: false,
                                    hideTrigger: true,
                                    decimalSeparator: '.',
                                    minValue: 0.01
                                },
                                {
                                    xtype: 'textfield',
                                    x: 0,
                                    y: 40,
                                    hidden: true,
                                    margin: 20,
                                    width: 335,
                                    fieldLabel: 'sign',
                                    labelAlign: 'top',
                                    name: 'sign',
                                    fieldStyle: 'background-color:#F0F8FF;font-size:13pt;font-weight:bold;text-align:left;color:red;'
                                },
                                {
                                    xtype: 'button',
                                    handler: function(button, e) {
                                        var form = button.findParentByType('form');
                                        var pay_id  = form.getForm().findField('payment_id').getValue();
                                        var summa  = form.getForm().findField('summa').getValue();
                                        var sign  = form.getForm().findField('sign').getValue();
                                        var xml  = form.getForm().findField('xml').getValue();
                                        //console.log(form);
                                        button.setParams({pay_id:pay_id,summa:summa,sign:sign,xml:xml});
                                    },
                                    x: 40,
                                    y: 240,
                                    formBind: true,
                                    height: 35,
                                    hidden: true,
                                    id: 'checkOplataTest',
                                    width: 310,
                                    href: 'marfin/pay.php',
                                    icon: 'resources/css/images/ico/door_in.png',
                                    scale: 'medium',
                                    text: 'СЭП «Интернет-Банкинг»  имитация',
                                    textAlign: 'left',
                                    tooltip: 'Очистить все выбранное'
                                },
                                {
                                    xtype: 'textareafield',
                                    x: 20,
                                    y: 120,
                                    height: 108,
                                    hidden: true,
                                    width: 345,
                                    fieldLabel: '',
                                    name: 'xml'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            flex: 1,
                            height: 39,
                            html: '<h3 class="mtb"><span><font style="text-align:justify;"><a href="https://i.mtb.ua/web/" target="_blank" >Перейти на сайт Интернет-Банкинга для оплаты</a></span></h3>'
                        }
                    ]
                }
            ]
        },
        {
            xtype: 'gridpanel',
            height: 193,
            id: 'grPayment',
            width: 898,
            title: 'Платежи через СЭП «Интернет-Банкинг» МарфинБанка',
            titleAlign: 'center',
            emptyText: 'нет данных по платежам',
            store: 'StPayment',
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'address_id',
                    text: 'Address_id'
                },
                {
                    xtype: 'datecolumn',
                    width: 75,
                    dataIndex: 'data',
                    menuDisabled: true,
                    text: 'Дата',
                    format: 'd-m-y'
                },
                {
                    xtype: 'numbercolumn',
                    width: 60,
                    dataIndex: 'payment_id',
                    menuDisabled: true,
                    text: 'Ид',
                    format: '0'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    dataIndex: 'kvartplata',
                    menuDisabled: true,
                    text: 'Кварт'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    dataIndex: 'otoplenie',
                    menuDisabled: true,
                    text: 'Отопл'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    dataIndex: 'ptn',
                    menuDisabled: true,
                    text: 'ПТН'
                },
                {
                    xtype: 'numbercolumn',
                    width: 70,
                    dataIndex: 'podogrev',
                    menuDisabled: true,
                    text: 'Подог'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    dataIndex: 'voda',
                    menuDisabled: true,
                    text: 'Вода'
                },
                {
                    xtype: 'numbercolumn',
                    width: 70,
                    dataIndex: 'stoki',
                    menuDisabled: true,
                    text: 'Стоки'
                },
                {
                    xtype: 'numbercolumn',
                    width: 55,
                    dataIndex: 'tbo',
                    menuDisabled: true,
                    text: 'ТБО'
                },
                {
                    xtype: 'numbercolumn',
                    width: 80,
                    dataIndex: 'summa',
                    menuDisabled: true,
                    text: 'Сумма'
                },
                {
                    xtype: 'numbercolumn',
                    width: 60,
                    dataIndex: 'commission',
                    menuDisabled: true,
                    text: 'Ком'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'prixod',
                    text: 'Prixod'
                },
                {
                    xtype: 'datecolumn',
                    hidden: true,
                    dataIndex: 'date_in',
                    text: 'Date_in'
                },
                {
                    xtype: 'gridcolumn',
                    hidden: true,
                    dataIndex: 'chek',
                    text: 'Chek'
                },
                {
                    xtype: 'gridcolumn',
                    width: 95,
                    dataIndex: 'status',
                    menuDisabled: true,
                    text: 'Статус'
                },
                {
                    xtype: 'actioncolumn',
                    width: 30,
                    menuDisabled: true,
                    icon: 'resources/css/images/ico/printer.png',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                var stUser = Ext.data.StoreManager.get("StUser");

                                //LOGIN & PASSWORD

                                var values =stUser.getAt(0);
                                var store = view.getStore();
                                var rec = store.getAt(rowIndex);
                                var pay_id = rec.get('payment_id');


                                if (pay_id) {
                                    var myMask= Ext.Msg.show({
                                        title:'Квитанция об оплате...',
                                        msg: 'Загрузка квитанции.Ожидайте...',
                                        buttons: Ext.Msg.CANCEL,
                                        wait: true,
                                        modal: true,
                                        icon: Ext.Msg.INFO
                                    });
                                    var report = 'raspechatkaOplataMarfin';
                                    var namereport = 'Квитанция';
                                    var value = {
                                        login:values.get('login'),
                                        address_id:values.get('address_id'),
                                        raion_id:values.get('raion_id'),
                                        report:report,
                                        what:report,
                                        user_id:values.get('user_id'),
                                        payment_id:pay_id

                                    };
                                    var tabPnCenter =  Ext.getCmp('tabFirstPage');//me.getTabPnCenter();
                                    //  console.log(tabPnCenter);
                                    var tab = tabPnCenter.child('#'+report);
                                    //console.log(tab);

                                    if (!tab) {
                                        // console.log(tab);

                                        tab  = tabPnCenter.add({
                                            xtype:'tabReport',
                                            title:namereport,
                                            itemid:''+report+''
                                        });

                                        // console.log(tab);

                                    }
                                    tabPnCenter.setActiveTab(tab);
                                    var reppan = tab.getComponent(0);
                                    QueryPaymentMarfin.getRaspechatka(value,function(data){
                                        if (data){
                                            reppan.update(data.content);
                                            Ext.REPORTCONTENT =data.content;
                                            Ext.REPORTSQL =data.sql;
                                            Ext.REPORTTITLE =report;
                                            myMask.close();

                                        } else {

                                            Ext.MessageBox.show({
                                                title: 'Ошибка ',
                                                msg: 'Документ не создан',
                                                buttons: Ext.MessageBox.OK,
                                                icon: Ext.MessageBox.ERROR
                                            });
                                            myMask.close();

                                        }
                                    });
                                }
                            },
                            getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                if (r.get('chek') === 0) {
                                    metaData = 'x-grid-center-icon';
                                } else {
                                    metaData = 'x-hide-display';
                                }
                                return metaData;
                            },
                            icon: 'resources/css/images/ico/printer.png'
                        }
                    ]
                }
            ]
        }
    ],

    onCheckboxfieldChange: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg1 = form.getForm().findField('dolg1').getValue();
        var dolg2 = form.getForm().findField('dolg2').getValue();
        var dolg3 = form.getForm().findField('dolg3').getValue();
        var dolg4 = form.getForm().findField('dolg4').getValue();
        var dolg5 = form.getForm().findField('dolg5').getValue();
        var dolg6 = form.getForm().findField('dolg6').getValue();
        var dolg7 = form.getForm().findField('dolg7').getValue();


        var dolg11 = 0 ;
        var dolg22 = 0 ;
        var dolg33 = 0 ;
        var dolg44 = 0 ;
        var dolg55 = 0 ;
        var dolg66 = 0 ;
        var dolg77 = 0 ;


        form.getForm().findField('cbNext8').setValue(true);

        if (newValue) {

            if(dolg1 > 0){
                form.getForm().findField('cbNext1').setValue(true);
                form.getForm().findField('oplata1').setValue(dolg1);
                form.getForm().findField('oplata1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                dolg11 = dolg1;

            } else {
                form.getForm().findField('cbNext1').setValue(false);
                form.getForm().findField('oplata1').setValue(0);
                form.getForm().findField('cbNext1').setDisabled(true);
                form.getForm().findField('oplata1').setFieldStyle('background-color: #fff; background-image: none;');
            }
            if(dolg2 > 0){
                form.getForm().findField('cbNext2').setValue(true);
                form.getForm().findField('oplata2').setValue(dolg2);
                form.getForm().findField('oplata2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                dolg22 = dolg2;

            } else {
                form.getForm().findField('cbNext2').setValue(false);
                form.getForm().findField('oplata2').setValue(0);
                form.getForm().findField('cbNext2').setDisabled(true);
                form.getForm().findField('oplata2').setFieldStyle('background-color: #fff; background-image: none;');
            }
            if(dolg3 > 0){
                form.getForm().findField('cbNext3').setValue(true);
                form.getForm().findField('oplata3').setValue(dolg3);
                form.getForm().findField('oplata3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                dolg33 = dolg3;

            } else {
                form.getForm().findField('cbNext3').setValue(false);
                form.getForm().findField('oplata3').setValue(0);
                form.getForm().findField('cbNext3').setDisabled(true);
                form.getForm().findField('oplata3').setFieldStyle('background-color: #fff; background-image: none;');
            }
            if(dolg4 > 0){
                form.getForm().findField('cbNext4').setValue(true);
                form.getForm().findField('oplata4').setValue(dolg4);
                form.getForm().findField('oplata4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                dolg44 = dolg4;

            } else {
                form.getForm().findField('cbNext4').setValue(false);
                form.getForm().findField('oplata4').setValue(0);
                form.getForm().findField('cbNext4').setDisabled(true);
                form.getForm().findField('oplata4').setFieldStyle('background-color: #fff; background-image: none;');
            }
            if(dolg5 > 0){
                form.getForm().findField('cbNext5').setValue(true);
                form.getForm().findField('oplata5').setValue(dolg5);
                form.getForm().findField('oplata5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                dolg55 = dolg5;

            } else {
                form.getForm().findField('cbNext5').setValue(false);
                form.getForm().findField('oplata5').setValue(0);
                form.getForm().findField('cbNext5').setDisabled(true);
                form.getForm().findField('oplata5').setFieldStyle('background-color: #fff; background-image: none;');
            }
            if(dolg6 > 0){
                form.getForm().findField('cbNext6').setValue(true);
                form.getForm().findField('oplata6').setValue(dolg6);
                form.getForm().findField('oplata6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                dolg66 = dolg6;

            } else {
                form.getForm().findField('cbNext6').setValue(false);
                form.getForm().findField('oplata6').setValue(0);
                form.getForm().findField('cbNext6').setDisabled(true);
                form.getForm().findField('oplata6').setFieldStyle('background-color: #fff; background-image: none;');
            }

              if(dolg7 > 0){
                form.getForm().findField('cbNext7').setValue(true);
                form.getForm().findField('oplata7').setValue(dolg7);
                form.getForm().findField('oplata7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                dolg77 = dolg7;

            } else {
                form.getForm().findField('cbNext7').setValue(false);
                form.getForm().findField('oplata7').setValue(0);
                form.getForm().findField('cbNext7').setDisabled(true);
                form.getForm().findField('oplata7').setFieldStyle('background-color: #fff; background-image: none;');
            }
            var dolg  = dolg11 + dolg22 + dolg33 + dolg44 + dolg55 + dolg66 + dolg77  ;

            if(dolg > 0){
                form.getForm().findField('newOplata').setValue(dolg);
                form.getForm().findField('dolg').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            } else {
                form.getForm().findField('cbNext').setValue(false);
                form.getForm().findField('newOplata').setValue(0);
                form.getForm().findField('cbNext').setDisabled(true);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');
            }

        }else {
            form.getForm().findField('cbNext').setValue(false);
            form.getForm().findField('cbNext1').setValue(false);
            form.getForm().findField('cbNext2').setValue(false);
            form.getForm().findField('cbNext3').setValue(false);
            form.getForm().findField('cbNext4').setValue(false);
            form.getForm().findField('cbNext5').setValue(false);
            form.getForm().findField('cbNext6').setValue(false);
            form.getForm().findField('cbNext7').setValue(false);

            form.getForm().findField('newOplata').setValue(0);

        }


        //form.down('#checkOplata').setDisabled(false);

    },

    onCheckboxfieldChange1: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg1').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata1').getValue();

        form.getForm().findField('cbNext8').setValue(true);

        if (form.getForm().findField('cbNext1').getValue() === true){
            form.getForm().findField('oplata1').setDisabled(false);
        } else {
            form.getForm().findField('oplata1').setDisabled(true);
        }

        if (newValue) {
            //console.log(newValue);
            if(dolg > 0) {
                form.getForm().findField('oplata1').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('oplata1').setValue(0);
                form.getForm().findField('cbNext1').setValue(false);
                form.getForm().findField('cbNext1').setDisabled(true);
                form.getForm().findField('oplata1').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg1').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {
            form.getForm().findField('oplata1').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata1').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg1').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onCheckboxfieldChange2: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg2').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata2').getValue();

        form.getForm().findField('cbNext8').setValue(true);
        if (form.getForm().findField('cbNext2').getValue() === true){
            form.getForm().findField('oplata2').setDisabled(false);
        } else {
            form.getForm().findField('oplata2').setDisabled(true);
        }
        if (newValue) {
            //   console.log(newValue);
            if(dolg > 0) {
                form.getForm().findField('oplata2').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('oplata2').setValue(0);
                form.getForm().findField('cbNext2').setValue(false);
                form.getForm().findField('cbNext2').setDisabled(true);
                form.getForm().findField('oplata2').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg2').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {
            form.getForm().findField('oplata2').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata2').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg2').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onNumberfieldChange1: function(field, newValue, oldValue, eOpts) {
          if (newValue !== oldValue){
                    //  console.log(newValue);
                    var form = field.findParentByType('form');
                    var oplata = 0;
                    var oplata2 = form.getForm().findField('oplata2').getValue();
                    var oplata3 = form.getForm().findField('oplata3').getValue();
                    var oplata4 = form.getForm().findField('oplata4').getValue();
                    var oplata5 = form.getForm().findField('oplata5').getValue();
                    var oplata6 = form.getForm().findField('oplata6').getValue();
                    var oplata7 = form.getForm().findField('oplata7').getValue();


                    form.getForm().findField('oplata1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                    form.getForm().findField('dolg1').setFieldStyle('background-color: #fff; background-image: none;');
                    form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');
                 //   form.down('#checkOplata').setDisabled(false);


                    oplata = newValue + oplata2 + oplata3 + oplata4 + oplata5 + oplata6 + oplata7;
                    var newOplata = form.getForm().findField('newOplata').setValue(oplata);

                }
    },

    onNumberfieldChange2: function(field, newValue, oldValue, eOpts) {
         if (newValue !== oldValue){
             var form = field.findParentByType('form');

             var oplata = 0;
             var oplata1 = form.getForm().findField('oplata1').getValue();
             var oplata3 = form.getForm().findField('oplata3').getValue();
             var oplata4 = form.getForm().findField('oplata4').getValue();
             var oplata5 = form.getForm().findField('oplata5').getValue();
             var oplata6 = form.getForm().findField('oplata6').getValue();
             var oplata7 = form.getForm().findField('oplata7').getValue();

             form.getForm().findField('oplata2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
             form.getForm().findField('dolg2').setFieldStyle('background-color: #fff; background-image: none;');
             form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');
             oplata = newValue + oplata1 + oplata3 + oplata4 + oplata5 + oplata6 + oplata7;
             form.getForm().findField('newOplata').setValue(oplata);

         }
    },

    onCheckboxfieldChange3: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg3').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata3').getValue();

        form.getForm().findField('cbNext8').setValue(true);
        if (form.getForm().findField('cbNext3').getValue() === true){
            form.getForm().findField('oplata3').setDisabled(false);
        } else {
            form.getForm().findField('oplata3').setDisabled(true);
        }
        if (newValue) {
            if(dolg > 0) {

                form.getForm().findField('oplata3').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {

                form.getForm().findField('oplata3').setValue(0);
                form.getForm().findField('cbNext3').setValue(false);
                form.getForm().findField('cbNext3').setDisabled(true);
                form.getForm().findField('oplata3').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg3').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {

            form.getForm().findField('oplata3').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata3').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg3').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onCheckboxfieldChange4: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg4').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata4').getValue();

        form.getForm().findField('cbNext8').setValue(true);
        if (form.getForm().findField('cbNext4').getValue() === true){
            form.getForm().findField('oplata4').setDisabled(false);
        } else {
            form.getForm().findField('oplata4').setDisabled(true);
        }
        if (newValue) {
            //   console.log(newValue);
            if(dolg > 0) {
                form.getForm().findField('oplata4').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('oplata4').setValue(0);
                form.getForm().findField('cbNext4').setValue(false);
                form.getForm().findField('cbNext4').setDisabled(true);
                form.getForm().findField('oplata4').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg4').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {
            form.getForm().findField('oplata4').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata4').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg4').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onCheckboxfieldChange7: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg7').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata7').getValue();

        form.getForm().findField('cbNext8').setValue(true);
        if (form.getForm().findField('cbNext7').getValue() === true){
            form.getForm().findField('oplata7').setDisabled(false);
        } else {
            form.getForm().findField('oplata7').setDisabled(true);
        }
        if (newValue) {
            //   console.log(newValue);
            if(dolg > 0) {
                form.getForm().findField('oplata7').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('oplata7').setValue(0);
                form.getForm().findField('cbNext7').setValue(false);
                form.getForm().findField('cbNext7').setDisabled(true);
                form.getForm().findField('oplata7').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg7').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {
            form.getForm().findField('oplata7').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata7').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg7').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onNumberfieldChange3: function(field, newValue, oldValue, eOpts) {
         if (newValue !== oldValue){
             var form = field.findParentByType('form');
             var oplata = 0;
             var oplata1 = form.getForm().findField('oplata1').getValue();
             var oplata2 = form.getForm().findField('oplata2').getValue();
             var oplata4 = form.getForm().findField('oplata4').getValue();
             var oplata5 = form.getForm().findField('oplata5').getValue();
             var oplata6 = form.getForm().findField('oplata6').getValue();
             var oplata7 = form.getForm().findField('oplata7').getValue();

             form.getForm().findField('oplata3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
             form.getForm().findField('dolg3').setFieldStyle('background-color: #fff; background-image: none;');
             form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');
             oplata = newValue + oplata1 + oplata2 + oplata4 + oplata5 + oplata6 + oplata7 ;
             var newOplata = form.getForm().findField('newOplata').setValue(oplata);

         }
    },

    onNumberfieldChange4: function(field, newValue, oldValue, eOpts) {
           if (newValue !== oldValue){
               //  console.log(newValue);
               var form = field.findParentByType('form');
               var oplata = 0;
               var oplata1 = form.getForm().findField('oplata1').getValue();
               var oplata2 = form.getForm().findField('oplata2').getValue();
               var oplata3 = form.getForm().findField('oplata3').getValue();
               var oplata5 = form.getForm().findField('oplata5').getValue();
               var oplata6 = form.getForm().findField('oplata6').getValue();
               var oplata7 = form.getForm().findField('oplata7').getValue();

               form.getForm().findField('oplata4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
               form.getForm().findField('dolg4').setFieldStyle('background-color: #fff; background-image: none;');
               form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');
               oplata = newValue + oplata1 + oplata2 + oplata3 + oplata5 + oplata6 + oplata7;
               var newOplata = form.getForm().findField('newOplata').setValue(oplata);


           }
    },

    onNumberfieldChange7: function(field, newValue, oldValue, eOpts) {
           if (newValue !== oldValue){
               var form = field.findParentByType('form');
               var oplata = 0;
               var oplata1 = form.getForm().findField('oplata1').getValue();
               var oplata2 = form.getForm().findField('oplata2').getValue();
               var oplata3 = form.getForm().findField('oplata3').getValue();
               var oplata4 = form.getForm().findField('oplata4').getValue();
               var oplata5 = form.getForm().findField('oplata5').getValue();
               var oplata6 = form.getForm().findField('oplata6').getValue();
               form.getForm().findField('oplata7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
               form.getForm().findField('dolg7').setFieldStyle('background-color: #fff; background-image: none;');
               form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');
               oplata = newValue + oplata1 + oplata2 + oplata3 + oplata4 + oplata5 + oplata6;
               var newOplata = form.getForm().findField('newOplata').setValue(oplata);


           }
    },

    onCheckboxfieldChange5: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg5').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata5').getValue();

        form.getForm().findField('cbNext8').setValue(true);
        if (form.getForm().findField('cbNext5').getValue() === true){
            form.getForm().findField('oplata5').setDisabled(false);
        } else {
            form.getForm().findField('oplata5').setDisabled(true);
        }
        if (newValue) {

            if(dolg > 0) {
                form.getForm().findField('oplata5').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('oplata5').setValue(0);
                form.getForm().findField('cbNext5').setValue(false);
                form.getForm().findField('cbNext5').setDisabled(true);
                form.getForm().findField('oplata5').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg5').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {
            form.getForm().findField('oplata5').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata5').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg5').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onNumberfieldChange5: function(field, newValue, oldValue, eOpts) {
         if (newValue !== oldValue){
             var form = field.findParentByType('form');
             var oplata = 0;
             var oplata1 = form.getForm().findField('oplata1').getValue();
             var oplata2 = form.getForm().findField('oplata2').getValue();
             var oplata4 = form.getForm().findField('oplata4').getValue();
             var oplata3 = form.getForm().findField('oplata3').getValue();
             var oplata6 = form.getForm().findField('oplata6').getValue();
             var oplata7 = form.getForm().findField('oplata7').getValue();

             form.getForm().findField('oplata5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
             form.getForm().findField('dolg5').setFieldStyle('background-color: #fff; background-image: none;');
             form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');
             oplata = newValue + oplata1 + oplata2 + oplata4 + oplata3 + oplata6 + oplata7;
             var newOplata = form.getForm().findField('newOplata').setValue(oplata);
         }
    },

    onCheckboxfieldChange6: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg6').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var oplata = form.getForm().findField('oplata6').getValue();

        form.getForm().findField('cbNext8').setValue(true);
        if (form.getForm().findField('cbNext6').getValue() === true){
            form.getForm().findField('oplata6').setDisabled(false);
        } else {
            form.getForm().findField('oplata6').setDisabled(true);
        }
        if (newValue) {
            if(dolg > 0) {
                form.getForm().findField('oplata6').setValue(dolg);
                form.getForm().findField('newOplata').setValue(value+dolg-oplata);
                form.getForm().findField('newOplata').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplata6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('oplata6').setValue(0);
                form.getForm().findField('cbNext6').setValue(false);
                form.getForm().findField('cbNext6').setDisabled(true);
                form.getForm().findField('oplata6').setFieldStyle('background-color: #fff; background-image: none;');
                form.getForm().findField('dolg6').setFieldStyle('background-color: #fff; background-image: none;');
            }
        }else {
            form.getForm().findField('oplata6').setValue(0);
            form.getForm().findField('newOplata').setValue(value-oplata);
            form.getForm().findField('oplata6').setFieldStyle('background-color: #fff; background-image: none;');
            form.getForm().findField('dolg6').setFieldStyle('background-color: #fff; background-image: none;');

        }
    },

    onNumberfieldChange6: function(field, newValue, oldValue, eOpts) {
         if (newValue !== oldValue){
             var form = field.findParentByType('form');
             var oplata = 0;
             var oplata1 = form.getForm().findField('oplata1').getValue();
             var oplata2 = form.getForm().findField('oplata2').getValue();
             var oplata4 = form.getForm().findField('oplata4').getValue();
             var oplata5 = form.getForm().findField('oplata5').getValue();
             var oplata3 = form.getForm().findField('oplata3').getValue();
             var oplata7 = form.getForm().findField('oplata7').getValue();

             form.getForm().findField('oplata6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
             form.getForm().findField('dolg6').setFieldStyle('background-color: #fff; background-image: none;');
             form.getForm().findField('dolg').setFieldStyle('background-color: #fff; background-image: none;');
             oplata = newValue + oplata1 + oplata2 + oplata4 + oplata5 + oplata3 + oplata7;
             var newOplata = form.getForm().findField('newOplata').setValue(oplata);
         }
    },

    onCheckboxfieldChange8: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');

        if (newValue) {
            form.getForm().findField('commission').setValue(3);
            form.getForm().findField('commission').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            field.setBoxLabel('согласен');


        }else {
            form.getForm().findField('commission').setValue(0);
            form.getForm().findField('commission').setFieldStyle('background-color: #fff; background-image: none;');
            field.setBoxLabel('без комиссии');


        }
    }

});